// Core data module — show scoring, queries, directors, theaters, best-of, browse
// Imports: shows.json (~1.3 MB), reviews.json (~3.8 MB), audience.json (~8 KB), buzz.json (~7 KB)
// Also imports getShowGrosses from data-grosses for browse page performance sort

import {
  computeShowData,
  ComputedShow,
  RawShow,
  RawReview,
  RawAudience,
  RawBuzzThread,
} from './engine';

import type { Director, Theater, TheaterStructuredTips, TheaterVenueScores, TheaterAccessibility, TheaterExternalLinks, BestOfCategory, BestOfList, BrowseList } from './data-types';
import { getShowGrosses } from './data-grosses';
import { getAudienceBuzz } from './data-audience';
import { isOperaShow } from './show-market';
import { featureFlags } from '@/config/feature-flags';
import { isHomepageNotable, notabilityRank, NOTABILITY_THRESHOLDS, type NotabilitySignals } from './homepage-notability';
import { getShowCommercial } from './data-commercial';
import { getShowAwards } from './data-awards';
import { BROWSE_PAGES, BrowsePageConfig, BrowseFilterContext, getAllBrowseSlugs as getBrowseSlugsFromConfig } from '@/config/browse-pages';
// Import raw data (loaded at build time for static generation)
import showsData from '../../data/shows.json';
import reviewsData from '../../data/reviews.json';
import audienceData from '../../data/audience.json';
import buzzData from '../../data/buzz.json';
// Pre-computed blog reviews for scoring (generated by prebuild)
import blogReviewsData from '../../data/blog-reviews-for-scoring.json';
// LLM-generated related show recommendations
import relatedShowsData from '../../data/related-shows.json';
// Theater metadata (capacity, tips)
import theaterMetaData from '../../data/theater-metadata.json';

// Type the imported data
const shows: RawShow[] = showsData.shows as RawShow[];
const baseReviews: RawReview[] = reviewsData.reviews as RawReview[];
const audience: RawAudience[] = audienceData.audience as RawAudience[];
const buzz: RawBuzzThread[] = buzzData.threads as RawBuzzThread[];

// Inject blog reviews as Tier 3 critic reviews
const reviews: RawReview[] = [
  ...baseReviews,
  ...(blogReviewsData.reviews as RawReview[]),
];

// Pre-index reviews by showId so computeShowData skips its O(N×M) per-show filter.
// Matches the eager pattern in src/lib/data-reviews.ts (outletReviewsMap/criticReviewsMap)
// and the byShowId index in src/lib/data-tony-noms.ts. Node scripts like
// scripts/compute-gold-lists.js already use this lookup; the web app is catching up.
const reviewsByShowId = new Map<string, RawReview[]>();
for (const r of reviews) {
  const arr = reviewsByShowId.get(r.showId);
  if (arr) arr.push(r);
  else reviewsByShowId.set(r.showId, [r]);
}

// Cache for computed shows
let computedShowsCache: ComputedShow[] | null = null;

/**
 * Get all shows with computed scores
 */
export function getAllShows(): ComputedShow[] {
  if (computedShowsCache) return computedShowsCache;

  computedShowsCache = shows
    .filter((show: any) => !show._devOnly)
    .map(show => computeShowData(show, reviewsByShowId.get(show.id) || [], audience, buzz));

  return computedShowsCache;
}

/**
 * Check if a show belongs to Broadway (default category).
 * Shows with no category or category='broadway' are Broadway shows.
 */
function isBroadwayShow(show: ComputedShow): boolean {
  return !show.category || show.category === 'broadway';
}

/**
 * Get all Broadway shows (excludes off-Broadway and west-end from public listings).
 * Use getAllShows() for internal queries that need all shows (e.g., static page generation).
 */
export function getBroadwayShows(): ComputedShow[] {
  return getAllShows().filter(isBroadwayShow);
}

/**
 * IDs to exclude from London listings — non-theatre experiences that crept into
 * the data set (e.g. ABBA Voyage is a hologram concert at a purpose-built arena,
 * not theatre). These shows still exist as detail pages but are filtered out of
 * the West End / Off-West End hubs and OG data.
 */
const HIDDEN_LONDON_IDS = new Set<string>([
  'abba-voyage-off-west-end-2026',
]);

/**
 * Get all London shows (West End + Off-West End)
 */
export function getWestEndShows(): ComputedShow[] {
  return getAllShows().filter(show =>
    (show.category === 'west-end' || show.category === 'off-west-end') &&
    !HIDDEN_LONDON_IDS.has(show.id)
  );
}

/**
 * Get all Off-Broadway shows
 */
export function getOffBroadwayShows(): ComputedShow[] {
  return getAllShows().filter(show => show.category === 'off-broadway');
}

// Ticket-buyer platforms that count toward a show's "curated audience footprint"
// for homepage notability (Path B). Reddit is excluded — see homepage-notability.ts.
const CURATED_AUDIENCE_SOURCES = ['showScore', 'mezzanine', 'theatr', 'broadwayCom'] as const;

function curatedAudienceFootprint(showId: string): number {
  const buzz = getAudienceBuzz(showId);
  if (!buzz?.sources) return 0;
  let total = 0;
  for (const key of CURATED_AUDIENCE_SOURCES) {
    const src = buzz.sources[key];
    if (src && typeof src.reviewCount === 'number') total += src.reviewCount;
  }
  return total;
}

function notabilitySignalsFor(show: ComputedShow): NotabilitySignals {
  return {
    status: show.status,
    type: show.type,
    isRevival: show.isRevival,
    tags: show.tags,
    t1Count: show.criticScore?.tier1Count ?? 0,
    reviewCount: show.criticScore?.reviewCount ?? 0,
    curatedAudience: curatedAudienceFootprint(show.id),
    homepageInclude: show.homepageInclude,
    homepageExclude: show.homepageExclude,
  };
}

/**
 * Off-Broadway shows notable enough to surface on the Broadway homepage grid.
 * The default homepage is Broadway-only; when Broadway openings are sparse the
 * grid goes stale, so we mix in a capped, high-signal set of OB shows. The rule
 * (two auto paths + manual override) lives in src/lib/homepage-notability.ts.
 *
 * Manual homepageInclude picks are always kept (never cut by the cap); the
 * remaining slots are filled by auto-qualifying shows ranked by notability.
 */
export function getNotableOffBroadwayShows(limit = NOTABILITY_THRESHOLDS.cap): ComputedShow[] {
  const eligible = getOffBroadwayShows()
    .map(show => ({ show, signals: notabilitySignalsFor(show) }))
    .filter(({ signals }) => isHomepageNotable(signals));

  const forced = eligible.filter(({ signals }) => signals.homepageInclude);
  const auto = eligible
    .filter(({ signals }) => !signals.homepageInclude)
    .sort((a, b) => notabilityRank(b.signals) - notabilityRank(a.signals));

  const remaining = Math.max(0, limit - forced.length);
  return [...forced, ...auto.slice(0, remaining)].map(e => e.show);
}

/**
 * Get all Opera shows (Met Opera productions, categorized as off-broadway for
 * routing but tagged type='opera'). Powers the /opera route + operascorecard.com.
 */
export function getOperaShows(): ComputedShow[] {
  return getAllShows().filter(show => isOperaShow(show));
}

/** 'la-traviata-off-broadway' → 'la-traviata', 'la-boheme-off-broadway-2025' → 'la-boheme-2025' */
export function getOperaTitleSlug(fullSlug: string): string {
  return fullSlug.replace(/-off-broadway/, '');
}

export function getOperaShowByTitleSlug(titleSlug: string): ComputedShow | undefined {
  return getOperaShows().find(s => getOperaTitleSlug(s.slug) === titleSlug);
}

/**
 * Get Off-West End shows only (excludes West End proper)
 */
export function getOffWestEndShows(): ComputedShow[] {
  return getAllShows().filter(show =>
    show.category === 'off-west-end' && !HIDDEN_LONDON_IDS.has(show.id)
  );
}

/**
 * Get market stats for the header market picker
 */
export function getMarketStats() {
  const bwShows = getBroadwayShows();
  const weShows = getWestEndShows();
  const obShows = getOffBroadwayShows();
  const oweShows = getOffWestEndShows();
  const bwOpen = bwShows.filter(s => s.status === 'open' || s.status === 'previews');
  const weOpen = weShows.filter(s => s.status === 'open' || s.status === 'previews');
  const obOpen = obShows.filter(s => s.status === 'open' || s.status === 'previews');
  const oweOpen = oweShows.filter(s => s.status === 'open' || s.status === 'previews');
  return {
    nyc: {
      openShows: bwOpen.length,
      theaters: new Set(bwOpen.map(s => s.venue).filter(Boolean)).size,
    },
    westEnd: {
      openShows: weOpen.length,
      theaters: new Set(weOpen.map(s => s.venue).filter(Boolean)).size,
    },
    offBroadway: {
      openShows: obOpen.length,
    },
    offWestEnd: {
      openShows: oweOpen.length,
    },
  };
}

/**
 * Get shows filtered by status (excludes off-Broadway from public listings)
 */
export function getShowsByStatus(status: 'open' | 'closed' | 'previews' | 'all', options?: { includeOffBroadway?: boolean }): ComputedShow[] {
  const allShows = getAllShows();
  const includeOB = options?.includeOffBroadway ?? false;
  const filtered = includeOB ? allShows : allShows.filter(isBroadwayShow);
  if (status === 'all') return filtered;
  return filtered.filter(show => show.status === status);
}

/**
 * Get currently running shows (default homepage view — Broadway only)
 */
export function getCurrentShows(): ComputedShow[] {
  return getShowsByStatus('open');
}

/**
 * Get a single show by slug
 */
export function getShowBySlug(slug: string): ComputedShow | undefined {
  return getAllShows().find(show => show.slug === slug);
}

/**
 * Get a single show by ID
 */
export function getShowById(id: string): ComputedShow | undefined {
  return getAllShows().find(show => show.id === id);
}

/**
 * Get all show slugs (for static generation)
 */
/**
 * Regional (non-NYC US) shows are hidden from EVERY pre-rendered/indexed surface
 * (detail page static params, OG, sitemap, search index) until the `regional`
 * feature flag is on. They are a distinct category, so listing getters already
 * exclude them; this gate covers the build-time slug sets so a flag-off push can
 * never publish an orphaned, Google-indexed regional page.
 */
function regionalSlugAllowed(show: any): boolean {
  return featureFlags.regional || show.category !== 'regional';
}

export function getAllShowSlugs(): string[] {
  return shows
    .filter((show: any) => !show._devOnly && regionalSlugAllowed(show))
    .map(show => show.slug);
}

// Pinned at module init so parallel build workers agree on the cutoff.
// In production this is recomputed per build (module re-evaluated per build worker).
// DO NOT reuse this constant in request-time code paths — warm serverless instances
// would keep a stale value indefinitely. Build-time only.
const BUILD_TIME_NOW = Date.now();

/**
 * Get slugs for shows worth pre-rendering: open, in previews, or closed within
 * the recency window (or scheduled to close in the future). Used by show/[slug]
 * page + opengraph-image generateStaticParams. Reads raw shows.json directly —
 * skips the expensive ComputedShow scoring graph that getShowBySlug() would
 * trigger for every slug.
 *
 * Typo'd far-future closingDates (e.g. 2099-01-01) are caught by validate-data.js
 * at the data layer; we don't filter them here to avoid excluding legitimate
 * long-range scheduled closures (some upcoming shows have closing dates 1-2 years
 * out at announcement time).
 *
 * BUILD-TIME ONLY: relies on BUILD_TIME_NOW pinned at module init. Calling this
 * from a request handler would return a result based on the build clock, not now.
 */
export function getRecentShowSlugs(windowDays = 180): string[] {
  const cutoff = BUILD_TIME_NOW - windowDays * 86400000;
  return shows
    .filter((s: any) =>
      !s._devOnly && regionalSlugAllowed(s) && (
        s.status === 'open' || s.status === 'previews' ||
        (s.closingDate != null && new Date(s.closingDate).getTime() > cutoff)
      )
    )
    .map(s => s.slug as string);
}

/**
 * Get slugs for the "hot" pre-render set: open or previews only. Used by
 * opengraph-image.tsx to keep high-social-share-volume shows pre-rendered
 * while letting closed/historical shows fall through to ISR (each pre-rendered
 * OG is ~870KB of .vercel/output artifact and ~250ms of build-time fetch +
 * Satori render). Closed shows are scraped rarely; first cold scrape takes
 * ~500ms then CDN-caches.
 *
 * BUILD-TIME ONLY: same caveat as getRecentShowSlugs() — relies on shows.json
 * snapshot at module init.
 */
export function getHotShowSlugs(): string[] {
  return shows
    .filter((s: any) =>
      !s._devOnly && regionalSlugAllowed(s) && (s.status === 'open' || s.status === 'previews')
    )
    .map(s => s.slug as string);
}

/**
 * Get shows sorted by composite score (excludes off-Broadway from public listings)
 */
export function getShowsSortedByCompositeScore(ascending = false): ComputedShow[] {
  return [...getAllShows()].filter(isBroadwayShow).sort((a, b) => {
    const scoreA = a.compositeScore ?? -1;
    const scoreB = b.compositeScore ?? -1;
    return ascending ? scoreA - scoreB : scoreB - scoreA;
  });
}

/**
 * Show IDs that have at least one NYT "Critic's Pick" review. Built once per process.
 *
 * Sources (union):
 * 1. data/nyt-critics-picks.json — scraped from the NYT spotlight page
 *    (nytimes.com/spotlight/theater-critics-picks). Covers the ~100 most
 *    recent picks (back to ~April 2024). URL-matched against our reviews
 *    after stripping query strings/fragments (fixes mismatches like
 *    `?searchResultPosition=1`).
 * 2. reviews.json `designation === 'Critics_Pick'` — written by the rebuild
 *    pipeline, which itself unions the spotlight list with data/designations.json
 *    (human-verified historical picks like Book of Mormon, Moulin Rouge, Six,
 *    Water for Elephants — older than the spotlight window).
 *
 * This makes the homepage shelf consistent with the per-review Critic's Pick
 * badge rendered by ReviewsList.tsx.
 */
let _nytCriticsPickShowIds: Set<string> | null = null;
function canonicalUrl(u: string): string {
  try {
    const url = new URL(u);
    return url.origin + url.pathname.replace(/\/+$/, '');
  } catch {
    return u;
  }
}
export function getNYTCriticsPickShowIds(): Set<string> {
  if (_nytCriticsPickShowIds) return _nytCriticsPickShowIds;
  const ids = new Set<string>();
  try {
    const picksData = require('../../data/nyt-critics-picks.json') as { urls: string[] };
    const pickUrlSet = new Set((picksData.urls || []).map(canonicalUrl));
    for (const r of baseReviews) {
      if (r.outletId !== 'nytimes' || !r.url) continue;
      if (pickUrlSet.has(canonicalUrl(r.url))) ids.add(r.showId);
    }
  } catch { /* file missing */ }
  // Also include any review already designated Critics_Pick — covers the
  // designations.json manual-pick path so the shelf matches the badge.
  for (const r of baseReviews) {
    if (r.designation === 'Critics_Pick') ids.add(r.showId);
  }
  _nytCriticsPickShowIds = ids;
  return _nytCriticsPickShowIds;
}

/**
 * Get data freshness info
 */
export function getDataFreshness() {
  return {
    showsLastUpdated: showsData._meta.lastUpdated,
    reviewsLastUpdated: reviewsData._meta.lastUpdated,
    audienceLastUpdated: audienceData._meta.lastUpdated,
    buzzLastUpdated: buzzData._meta.lastUpdated,
  };
}

/**
 * Get raw data counts for stats
 */
export function getDataStats() {
  const broadwayShows = getBroadwayShows();
  const totalReviews = broadwayShows.reduce((sum, show) => sum + (show.criticScore?.reviewCount || 0), 0);

  // Count unique outlets and critics from Broadway reviews only (consistent with show counts)
  const broadwayIds = new Set(broadwayShows.map(s => s.id));
  const broadwayReviews = baseReviews.filter(r => broadwayIds.has(r.showId));
  const uniqueOutlets = new Set(broadwayReviews.map(r => r.outletId));
  const uniqueCritics = new Set(broadwayReviews.map(r => r.criticName).filter(Boolean));

  return {
    totalShows: broadwayShows.filter(s => (s.criticScore?.reviewCount || 0) > 0).length,
    openShows: broadwayShows.filter(s => s.status === 'open').length,
    closedShows: broadwayShows.filter(s => s.status === 'closed').length,
    totalReviews,
    totalOutlets: uniqueOutlets.size,
    totalCritics: uniqueCritics.size,
    totalAudiencePlatforms: audience.length,
    totalBuzzThreads: buzz.length,
  };
}

/**
 * Get the most recent data update timestamp for a show
 * Returns ISO string of the most recent update across core data sources
 */
export function getShowLastUpdated(showId: string): string | null {
  const timestamps: Date[] = [];

  try {
    if (showsData._meta?.lastUpdated) {
      timestamps.push(new Date(showsData._meta.lastUpdated));
    }
  } catch { /* ignore */ }

  try {
    if (reviewsData._meta?.lastUpdated) {
      timestamps.push(new Date(reviewsData._meta.lastUpdated));
    }
  } catch { /* ignore */ }

  try {
    if (audienceData._meta?.lastUpdated) {
      timestamps.push(new Date(audienceData._meta.lastUpdated));
    }
  } catch { /* ignore */ }

  try {
    if (buzzData._meta?.lastUpdated) {
      timestamps.push(new Date(buzzData._meta.lastUpdated));
    }
  } catch { /* ignore */ }

  if (timestamps.length === 0) return null;

  const mostRecent = new Date(Math.max(...timestamps.map(d => d.getTime())));
  return mostRecent.toISOString();
}

/**
 * Get upcoming shows (in previews) - sorted by soonest opening date first.
 * Requires opening date (excludes undated announced shows).
 */
export function getUpcomingShows(): ComputedShow[] {
  return getBroadwayShows()
    .filter(show => (show.status === 'previews' || show.status === 'upcoming') && show.openingDate)
    .sort((a, b) => new Date(a.openingDate).getTime() - new Date(b.openingDate).getTime());
}

// ============================================
// Director Queries
// ============================================

export function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

/**
 * Get all unique directors with their shows
 */
export function getAllDirectors(): Director[] {
  const allShows = getBroadwayShows();
  const directorMap = new Map<string, ComputedShow[]>();

  for (const show of allShows) {
    const directors = show.creativeTeam?.filter(m =>
      m.role.toLowerCase().includes('director') &&
      !m.role.toLowerCase().includes('music director') &&
      !m.role.toLowerCase().includes('artistic director')
    ) || [];

    for (const director of directors) {
      const existing = directorMap.get(director.name) || [];
      existing.push(show);
      directorMap.set(director.name, existing);
    }
  }

  return Array.from(directorMap.entries()).map(([name, shows]) => {
    const scoredShows = shows.filter(s => s.criticScore?.score);
    const avgScore = scoredShows.length > 0
      ? Math.round(scoredShows.reduce((sum, s) => sum + (s.criticScore?.score || 0), 0) / scoredShows.length)
      : null;

    return {
      name,
      slug: slugify(name),
      shows,
      avgScore,
      showCount: shows.length,
    };
  }).sort((a, b) => b.showCount - a.showCount);
}

/**
 * Get a single director by slug
 */
export function getDirectorBySlug(slug: string): Director | undefined {
  return getAllDirectors().find(d => d.slug === slug);
}

/**
 * Get all director slugs (for static generation)
 */
export function getAllDirectorSlugs(): string[] {
  return getAllDirectors().map(d => d.slug);
}

// ============================================
// Theater Queries
// ============================================

/**
 * Get all unique theaters with their shows (memoized)
 */
let _theatersCache: Theater[] | null = null;
export function getAllTheaters(): Theater[] {
  if (_theatersCache) return _theatersCache;

  const allShows = getBroadwayShows();
  const theaterMap = new Map<string, { shows: ComputedShow[]; address?: string }>();

  for (const show of allShows) {
    const existing = theaterMap.get(show.venue) || { shows: [], address: show.theaterAddress };
    existing.shows.push(show);
    if (show.theaterAddress) existing.address = show.theaterAddress;
    theaterMap.set(show.venue, existing);
  }

  const meta = theaterMetaData as unknown as Record<string, { capacity?: number; tips?: string; yearBuilt?: number; operator?: string; formerNames?: string[]; structuredTips?: TheaterStructuredTips; images?: { exterior?: string; interior?: string; attribution?: string }; venueScores?: Omit<TheaterVenueScores, 'overall'>; accessibility?: TheaterAccessibility; externalLinks?: TheaterExternalLinks }>;

  _theatersCache = Array.from(theaterMap.entries())
    .filter(([name]) => !name.startsWith('_'))
    .map(([name, data]) => {
      const currentShow = data.shows.find(s => s.status === 'open' || s.status === 'previews' || s.status === 'upcoming');
      const theaterMeta = meta[name];

      // Compute overall venue score from individual dimensions
      const rawScores = theaterMeta?.venueScores;
      let venueScores: TheaterVenueScores | undefined;
      if (rawScores) {
        const dims = [rawScores.sightlines, rawScores.sound, rawScores.comfort, rawScores.ambiance, rawScores.facilities].filter((v): v is number => v != null);
        venueScores = {
          ...rawScores,
          overall: dims.length > 0 ? Math.round((dims.reduce((a, b) => a + b, 0) / dims.length) * 10) / 10 : undefined,
        };
      }

      return {
        name,
        slug: slugify(name),
        address: data.address,
        capacity: theaterMeta?.capacity,
        yearBuilt: theaterMeta?.yearBuilt,
        operator: theaterMeta?.operator,
        formerNames: theaterMeta?.formerNames,
        tips: theaterMeta?.tips,
        structuredTips: theaterMeta?.structuredTips,
        images: theaterMeta?.images,
        venueScores,
        accessibility: theaterMeta?.accessibility,
        externalLinks: theaterMeta?.externalLinks,
        currentShow,
        allShows: data.shows.sort((a, b) => {
          if (!a.openingDate && !b.openingDate) return 0;
          if (!a.openingDate) return 1;
          if (!b.openingDate) return -1;
          return new Date(b.openingDate).getTime() - new Date(a.openingDate).getTime();
        }),
        showCount: data.shows.length,
      };
    }).sort((a, b) => b.showCount - a.showCount);

  // Warn about shows with venues that don't match any theater metadata
  const theaterSlugs = new Set(_theatersCache.map(t => t.slug));
  const metaKeys = new Set(Object.keys(meta).filter(k => k !== '_meta'));
  for (const show of allShows) {
    if (show.venue && !metaKeys.has(show.venue) && show.category !== 'west-end' && show.category !== 'off-west-end' && show.category !== 'off-broadway') {
      const venueSlug = slugify(show.venue);
      if (!theaterSlugs.has(venueSlug)) {
        console.warn(`[Theater Scorecard] Unmatched theater: "${show.venue}" (show: ${show.id})`);
      }
    }
  }

  return _theatersCache;
}

/**
 * Get a single theater by slug
 */
export function getTheaterBySlug(slug: string): Theater | undefined {
  return getAllTheaters().find(t => t.slug === slug);
}

/**
 * Get all theater slugs (for static generation)
 */
export function getAllTheaterSlugs(): string[] {
  return getAllTheaters().map(t => t.slug);
}

/**
 * Get all London venues (West End + Off-West End) as Theater objects.
 *
 * Stub implementation for the WE launch (2026-04-13): unlike Broadway theaters
 * we have no curated metadata (capacity, tips, structuredTips, venueScores),
 * so every field outside of `name`, `slug`, `address`, `currentShow`,
 * `allShows`, and `showCount` is left undefined and the UI renders "—".
 * Enrichment (Wikipedia/IBDB/curated tips) tracked as follow-up.
 */
let _londonTheatersCache: Theater[] | null = null;
export function getAllLondonTheaters(): Theater[] {
  if (_londonTheatersCache) return _londonTheatersCache;

  const allShows = getWestEndShows(); // includes off-west-end, excludes hidden
  const theaterMap = new Map<string, { shows: ComputedShow[]; address?: string }>();

  // Skip placeholder venues — 10 announced shows list "TBA" which would create
  // a fake /west-end/theater/tba page with 10 "past shows."
  const PLACEHOLDER_VENUES = new Set(['TBA', 'TBD', 'tba', 'tbd', 'Unknown', 'unknown']);

  for (const show of allShows) {
    if (!show.venue || PLACEHOLDER_VENUES.has(show.venue)) continue;
    const existing = theaterMap.get(show.venue) || { shows: [], address: show.theaterAddress };
    existing.shows.push(show);
    if (show.theaterAddress) existing.address = show.theaterAddress;
    theaterMap.set(show.venue, existing);
  }

  _londonTheatersCache = Array.from(theaterMap.entries())
    .filter(([name]) => !name.startsWith('_'))
    .map(([name, data]) => {
      const currentShow = data.shows.find(
        s => s.status === 'open' || s.status === 'previews' || s.status === 'upcoming'
      );
      return {
        name,
        slug: slugify(name),
        address: data.address,
        currentShow,
        allShows: data.shows.sort((a, b) => {
          if (!a.openingDate && !b.openingDate) return 0;
          if (!a.openingDate) return 1;
          if (!b.openingDate) return -1;
          return new Date(b.openingDate).getTime() - new Date(a.openingDate).getTime();
        }),
        showCount: data.shows.length,
      };
    })
    .sort((a, b) => b.showCount - a.showCount);

  return _londonTheatersCache;
}

/**
 * Get a single London venue by slug
 */
export function getLondonTheaterBySlug(slug: string): Theater | undefined {
  return getAllLondonTheaters().find(t => t.slug === slug);
}

/**
 * Get all London theater slugs (for static generation)
 */
export function getAllLondonTheaterSlugs(): string[] {
  return getAllLondonTheaters().map(t => t.slug);
}

// ============================================
// Best-of List Queries
// ============================================

const BEST_OF_CONFIG: Record<BestOfCategory, { title: string; description: string; filter: (show: ComputedShow) => boolean }> = {
  'musicals': {
    title: 'Best Broadway Musicals',
    description: 'Every Broadway musical ranked by aggregated critic scores from NYT, Variety, Vulture & 400+ outlets. See which are must-sees right now. Updated weekly.',
    filter: (show) => show.type === 'musical' && show.status === 'open',
  },
  'plays': {
    title: 'Best Broadway Plays',
    description: 'Every Broadway play ranked by aggregated critic scores from 400+ outlets. Find the must-see dramas and comedies playing now.',
    filter: (show) => show.type === 'play' && show.status === 'open',
  },
  'new-shows': {
    title: 'Best New Broadway Shows',
    description: 'The highest-rated Broadway shows that opened this season, ranked by aggregated critic scores from NYT, Variety, Vulture & 400+ outlets.',
    filter: (show) => {
      const openDate = new Date(show.openingDate);
      const now = new Date();
      const seasonStartYear = now.getMonth() >= 8 ? now.getFullYear() : now.getFullYear() - 1;
      const seasonStart = new Date(`${seasonStartYear}-09-01`);
      return show.status === 'open' && openDate >= seasonStart;
    },
  },
  'highest-rated': {
    title: 'Top 10 Highest Rated Broadway Shows',
    description: 'The 10 highest-rated Broadway shows right now based on aggregated critic scores from NYT, Variety, Vulture & 400+ outlets. Updated weekly.',
    filter: (show) => show.status === 'open' && show.criticScore?.score !== undefined,
  },
  'family': {
    title: 'Best Broadway Shows for Families',
    description: 'The best Broadway shows for kids and families, ranked by critics. Find age-appropriate musicals and plays the whole family will love.',
    filter: (show) => {
      const ageRec = show.ageRecommendation?.toLowerCase() || '';
      const tags = show.tags?.map(t => t.toLowerCase()) || [];
      return show.status === 'open' && (
        ageRec.includes('all ages') ||
        ageRec.includes('ages 6') ||
        ageRec.includes('ages 8') ||
        tags.includes('family')
      );
    },
  },
  'comedy': {
    title: 'Best Broadway Comedies',
    description: 'The funniest shows on Broadway right now, ranked by aggregated critic scores from 400+ outlets. Find the laughs you need. Updated weekly.',
    filter: (show) => {
      const tags = show.tags?.map(t => t.toLowerCase()) || [];
      return show.status === 'open' && tags.includes('comedy');
    },
  },
  'drama': {
    title: 'Best Broadway Dramas',
    description: 'The best dramas on Broadway right now, ranked by aggregated critic scores from 400+ outlets. Powerful plays currently captivating audiences and critics alike.',
    filter: (show) => {
      const tags = show.tags?.map(t => t.toLowerCase()) || [];
      return show.status === 'open' && tags.includes('drama');
    },
  },
};

/**
 * Get a best-of list by category
 */
export function getBestOfList(category: BestOfCategory): BestOfList | undefined {
  const config = BEST_OF_CONFIG[category];
  if (!config) return undefined;

  const allShows = getBroadwayShows();
  const filteredShows = allShows
    .filter(config.filter)
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .slice(0, 10);

  return {
    category,
    title: config.title,
    description: config.description,
    shows: filteredShows,
  };
}

/**
 * Get all best-of categories (for static generation)
 */
export function getAllBestOfCategories(): BestOfCategory[] {
  return Object.keys(BEST_OF_CONFIG) as BestOfCategory[];
}

// ============================================
// Browse Page Queries
// ============================================

/**
 * Get filtered and sorted shows for a browse page
 */
export function getBrowseList(slug: string): BrowseList | undefined {
  const config = BROWSE_PAGES[slug];
  if (!config) return undefined;

  const allShows = config.source === 'west-end' ? getWestEndShows()
    : config.source === 'off-broadway' ? getOffBroadwayShows()
    : config.source === 'off-west-end' ? getOffWestEndShows()
    : getBroadwayShows();

  // Context for data-dependent filters and custom sorts
  const ctx: BrowseFilterContext = { getAudienceBuzz, getShowCommercial, getShowAwards, getShowGrosses };

  let filteredShows = config.dataFilter
    ? allShows.filter(show => config.dataFilter!(show, ctx))
    : config.filter
    ? allShows.filter(config.filter)
    : allShows;

  // customSort and sort are mutually exclusive — customSort skips the sort switch
  if (config.customSort) {
    filteredShows = config.customSort(filteredShows, ctx);
  } else if (config.sort === 'score') {
    filteredShows = filteredShows.sort((a, b) => {
      const aScore = a.criticScore?.score;
      const bScore = b.criticScore?.score;
      if (aScore != null && bScore == null) return -1;
      if (aScore == null && bScore != null) return 1;
      if (aScore == null && bScore == null) return 0;
      return bScore! - aScore!;
    });
  } else if (config.sort === 'opening-date') {
    filteredShows = filteredShows.sort((a, b) => {
      if (!a.openingDate && !b.openingDate) return 0;
      if (!a.openingDate) return 1;
      if (!b.openingDate) return -1;
      return new Date(b.openingDate).getTime() - new Date(a.openingDate).getTime();
    });
  } else if (config.sort === 'opening-date-asc') {
    filteredShows = filteredShows.sort((a, b) => {
      if (!a.openingDate && !b.openingDate) return 0;
      if (!a.openingDate) return 1;
      if (!b.openingDate) return -1;
      return new Date(a.openingDate).getTime() - new Date(b.openingDate).getTime();
    });
  } else if (config.sort === 'closing-date') {
    filteredShows = filteredShows.sort((a, b) => {
      if (!a.closingDate) return 1;
      if (!b.closingDate) return -1;
      return new Date(a.closingDate).getTime() - new Date(b.closingDate).getTime();
    });
  } else if (config.sort === 'title') {
    filteredShows = filteredShows.sort((a, b) =>
      a.title.localeCompare(b.title)
    );
  } else if (config.sort === 'performances') {
    filteredShows = filteredShows.sort((a, b) => {
      const aGrosses = getShowGrosses(a.slug);
      const bGrosses = getShowGrosses(b.slug);
      const aPerf = aGrosses?.allTime?.performances ?? 0;
      const bPerf = bGrosses?.allTime?.performances ?? 0;
      return bPerf - aPerf;
    });
  }

  if (config.limit) {
    filteredShows = filteredShows.slice(0, config.limit);
  }

  return {
    config,
    shows: filteredShows,
  };
}

/**
 * Get all browse page slugs for static generation
 */
export function getAllBrowseSlugs(): string[] {
  return getBrowseSlugsFromConfig();
}

/**
 * Get related shows — LLM-generated lookup with algorithmic fallback
 */
// Strip year suffix to get base title for same-show detection
function baseTitle(title: string): string {
  return title.toLowerCase().replace(/\s*\(\d{4}\)\s*$/, '').trim();
}

function isSameShow(a: ComputedShow, b: ComputedShow): boolean {
  return a.id === b.id || baseTitle(a.title) === baseTitle(b.title);
}

export function getRelatedShows(show: ComputedShow, limit = 6): ComputedShow[] {
  const entry = (relatedShowsData as Record<string, unknown> & { shows: Record<string, { relatedIds: string[]; relatedOpenIds?: string[]; relatedClosedIds?: string[] }> }).shows?.[show.id];
  if (entry?.relatedIds?.length) {
    const allShows = getAllShows();
    const idMap = new Map(allShows.map(s => [s.id, s]));
    const slugMap = new Map(allShows.map(s => [s.slug, s]));
    const showCity = getCity(show.category);
    return entry.relatedIds
      .map((id: string) => idMap.get(id) || slugMap.get(id))
      .filter((s): s is ComputedShow => s != null && !isSameShow(s, show) && getCity(s.category) === showCity)
      .slice(0, limit);
  }
  return getRelatedShowsAlgorithmic(show, limit);
}

function getCity(category: string | undefined): string {
  const cat = category || 'broadway';
  if (cat === 'broadway' || cat === 'off-broadway') return 'nyc';
  if (cat === 'west-end' || cat === 'off-west-end') return 'london';
  // 'regional' (non-NYC US tryouts) intentionally returns its own bucket ('regional'),
  // so related-shows only pull other regional shows — never NYC/London productions.
  return cat;
}

export function getRelatedShowsOpen(show: ComputedShow, limit = 6): ComputedShow[] {
  const entry = (relatedShowsData as Record<string, unknown> & { shows: Record<string, { relatedOpenIds?: string[] }> }).shows?.[show.id];
  if (entry?.relatedOpenIds?.length) {
    const allShows = getAllShows();
    const idMap = new Map(allShows.map(s => [s.id, s]));
    const slugMap = new Map(allShows.map(s => [s.slug, s]));
    const showCity = getCity(show.category);
    return entry.relatedOpenIds
      .map((id: string) => idMap.get(id) || slugMap.get(id))
      .filter((s): s is ComputedShow => s != null && (s.status === 'open' || s.status === 'previews' || s.status === 'upcoming') && !isSameShow(s, show) && getCity(s.category) === showCity)
      .slice(0, limit);
  }
  // Fallback: filter algorithmic results to open/previews/upcoming
  return getRelatedShowsAlgorithmic(show, limit * 3)
    .filter(s => s.status === 'open' || s.status === 'previews' || s.status === 'upcoming')
    .slice(0, limit);
}

export function getRelatedShowsClosed(show: ComputedShow, limit = 6): ComputedShow[] {
  const entry = (relatedShowsData as Record<string, unknown> & { shows: Record<string, { relatedClosedIds?: string[] }> }).shows?.[show.id];
  if (entry?.relatedClosedIds?.length) {
    const allShows = getAllShows();
    const idMap = new Map(allShows.map(s => [s.id, s]));
    const slugMap = new Map(allShows.map(s => [s.slug, s]));
    const showCity = getCity(show.category);
    return entry.relatedClosedIds
      .map((id: string) => idMap.get(id) || slugMap.get(id))
      .filter((s): s is ComputedShow => s != null && s.status === 'closed' && !isSameShow(s, show) && getCity(s.category) === showCity)
      .slice(0, limit);
  }
  // Fallback: filter algorithmic results to closed
  return getRelatedShowsAlgorithmic(show, limit * 3)
    .filter(s => s.status === 'closed')
    .slice(0, limit);
}

/**
 * Find other productions of the same show across markets/years
 */
export function getOtherProductions(show: ComputedShow): ComputedShow[] {
  const normalize = (t: string) => t.toLowerCase().replace(/[\u2018\u2019\u2032'']/g, "'").replace(/[^\w\s']/g, '').trim();
  const baseTitle = normalize(show.title);
  // 'regional' last (4): when a regional tryout later transfers to Broadway, the
  // Broadway production (0) leads the cross-production list and the tryout trails it.
  const marketOrder: Record<string, number> = { broadway: 0, 'west-end': 1, 'off-west-end': 2, 'off-broadway': 3, regional: 4 };
  return getAllShows()
    .filter(s => s.id !== show.id && normalize(s.title) === baseTitle)
    .sort((a, b) => {
      const catA = marketOrder[(a.category || 'broadway')] ?? 3;
      const catB = marketOrder[(b.category || 'broadway')] ?? 3;
      if (catA !== catB) return catA - catB;
      return (b.openingDate || '').localeCompare(a.openingDate || '');
    });
}

/**
 * Algorithmic fallback for shows not in the LLM-generated JSON
 */
function getRelatedShowsAlgorithmic(show: ComputedShow, limit = 6): ComputedShow[] {
  const allShows = getAllShows();

  // Precompute creative team lookup (name → role)
  const currentCreatives = new Map<string, string>();
  for (const m of show.creativeTeam || []) {
    currentCreatives.set(m.name.toLowerCase(), m.role.toLowerCase());
  }

  const currentTags = new Set(show.tags || []);
  const currentYear = show.openingDate ? new Date(show.openingDate).getFullYear() : 2020;
  const currentScore = show.criticScore?.score ?? null;

  // Score bands for proximity matching
  const getBand = (score: number | null) => {
    if (score === null) return -1;
    if (score >= 90) return 3;
    if (score >= 75) return 2;
    if (score >= 60) return 1;
    return 0;
  };
  const currentBand = getBand(currentScore);

  // Thematic vs structural tags
  const thematicTags = new Set(['comedy', 'drama', 'romantic', 'family', 'historical', 'fantasy', 'thriller', 'biographical']);
  const structuralTags = new Set(['jukebox', 'immersive', 'one-person-show', 'concert', 'revue']);

  // Role weights for creative team matching
  const roleWeight = (role: string): number => {
    const r = role.toLowerCase();
    if (r === 'director') return 8;
    if (r === 'book' || r === 'playwright' || r === 'composer' || r === 'music' || r === 'lyrics' || r === 'lyricist') return 7;
    if (r === 'choreographer') return 5;
    return 2;
  };

  const showCity = getCity(show.category);
  const scored = allShows
    .filter(s => !isSameShow(s, show) && (s.criticScore?.reviewCount ?? 0) >= 5 && getCity(s.category) === showCity)
    .map(candidate => {
      let score = 0;

      // Type match (musical/play) — strong signal
      if (candidate.type === show.type) score += 10;

      // Creative team overlap (role-weighted)
      for (const member of candidate.creativeTeam || []) {
        if (currentCreatives.has(member.name.toLowerCase())) {
          score += roleWeight(member.role);
        }
      }

      // Tag overlap (category-weighted)
      for (const tag of candidate.tags || []) {
        if (!currentTags.has(tag)) continue;
        if (thematicTags.has(tag)) score += 4;
        else if (structuralTags.has(tag)) score += 2;
        // Skip meta tags like 'tony-winner', 'lottery', 'rush'
      }

      // Score band proximity
      const candidateBand = getBand(candidate.criticScore?.score ?? null);
      if (currentBand >= 0 && candidateBand >= 0) {
        if (candidateBand === currentBand) score += 3;
        else if (Math.abs(candidateBand - currentBand) === 1) score += 1;
      }

      // Temporal proximity
      const candidateYear = candidate.openingDate ? new Date(candidate.openingDate).getFullYear() : 2020;
      const yearDiff = Math.abs(currentYear - candidateYear);
      if (yearDiff <= 2) score += 3;
      else if (yearDiff <= 5) score += 1;

      // Currently open/previews boost
      if (candidate.status === 'open' || candidate.status === 'previews' || candidate.status === 'upcoming') score += 3;

      return { show: candidate, score };
    })
    .filter(({ score }) => score >= 12) // Minimum threshold — must match on type + at least one other signal
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);

  return scored.map(s => s.show);
}

// Export types
export type { ComputedShow };
export type { BrowsePageConfig } from '@/config/browse-pages';
