/**
 * Social Pulse data loader — reads the compact sibling public file
 * generated by scripts/fetch-social-pulse.js.
 *
 * We read from a SIBLING file (public/data/shows/{id}.social.json) rather
 * than the main show JSON to avoid race conditions with the nightly
 * generate-mobile-show-details.js rebuild — see that script's comment
 * plus the plan-review pre-mortem scenario.
 *
 * Returns null if the file doesn't exist (show never scraped, or scraper
 * hasn't run yet). The card component renders nothing for null.
 */

import fs from 'fs';
import path from 'path';

import type { SocialPulsePayload } from '@/components/show-page/SocialPulseCard';

const PUBLIC_SHOWS_DIR = path.join(process.cwd(), 'public', 'data', 'shows');
const SOCIAL_PULSE_DIR = path.join(process.cwd(), 'data', 'social-pulse');

/**
 * Raw social pulse file written by scripts/fetch-social-pulse.js — lives in
 * data/social-pulse/{show-id}.json. Unlike the compact public sibling file,
 * this uses the full field names and has `compositeScore` + `rank` computed
 * by compute-social-pulse-ranks.js.
 *
 * Consumed by the /trending page at build time. Only a subset of fields
 * is typed here — enough for ranking, tier display, and top-quote cards.
 */
export interface RawSocialPulse {
  _v: number;
  showId: string;
  showTitle: string;
  market: 'Broadway' | 'West End' | 'Off-Broadway' | 'Off-West End';
  fetchedAt: string;
  tier: 'Buzzing' | 'Rising' | 'Steady' | 'Troubled' | 'BuildingBaseline' | 'Hidden';
  volume: number;
  positivePct: number;
  weekOverWeekPct: number | null;
  baselineMultiple: number | null;
  platformBreakdown: { x: number; tiktok: number; instagram: number; reddit?: number };
  topQuotes: Array<{ text: string; platform: string; author: string | null; url: string | null }>;
  rank?: { position: number; total: number; text: string } | null;
  compositeScore?: number;
}

/**
 * A social-pulse row that has been materialized with a guaranteed numeric
 * composite score — returned by `getTopTrendingShows`. Consumers can rely on
 * `compositeScore: number` without the `?? 0` dance at the call site.
 */
export type TrendingPick = RawSocialPulse & { compositeScore: number };

/**
 * Minimum 7-day mention volume required for a show to be eligible for the
 * /trending leaderboard. The underlying scorer only hides shows below 20
 * mentions (MIN_MENTIONS_FOR_CARD in social-pulse-scorer.js), which is fine
 * for per-show cards but would surface low-signal noise on a "buzziest
 * shows" page. 50 keeps every current top-10 entry comfortably in-bounds
 * while filtering out the long tail. Tune higher if top-10s start looking
 * thin; lower if markets don't fill.
 */
export const MIN_TRENDING_VOLUME = 50;

/**
 * Maximum age (days) of a social-pulse fetch before we treat it as stale and
 * stop surfacing it. The fetcher (update-social-pulse.yml) runs weekly and only
 * refreshes open/previews shows (scripts/lib/list-running-shows.js), so an
 * upcoming or closed show keeps a FROZEN file indefinitely — e.g. School Girls;
 * Or, The African Mean Girls Play sat at a 2026-04-13 fetch for 6+ weeks while
 * upcoming. Without this guard the show page and /trending render that stale
 * data under a "last 7 days" framing. 14 days = one full weekly cycle plus a
 * week of slack for a late/missed cron, so a still-running show never flickers
 * off mid-week. Mirrors the newsletter guard in scripts/newsletter/generate.mjs.
 */
export const MAX_SOCIAL_PULSE_AGE_DAYS = 14;

/**
 * True if `fetchedAtISO` is present, parseable, and within
 * MAX_SOCIAL_PULSE_AGE_DAYS of `now`. A missing/garbled timestamp is treated as
 * stale (safe direction — better to hide than to show undated data). `now` is a
 * parameter (not Date.now()) so callers stay testable; build-time callers pass
 * the default. Output therefore depends on build date — intentional, since the
 * data genuinely ages, and CI + local builds on the same day stay in sync.
 */
export function isFreshPulse(fetchedAtISO: string | null | undefined, now: Date = new Date()): boolean {
  if (!fetchedAtISO) return false;
  const fetched = Date.parse(fetchedAtISO);
  if (Number.isNaN(fetched)) return false;
  const ageMs = now.getTime() - fetched;
  return ageMs <= MAX_SOCIAL_PULSE_AGE_DAYS * 24 * 60 * 60 * 1000;
}

/**
 * Synchronously reads the social pulse payload for a show. Safe to call
 * from React server components and getStaticProps equivalents.
 *
 * File-not-found is NOT an error — most shows won't have a file yet, and
 * any that do will have been generated by the weekly workflow. We return
 * null silently and let the card component no-op.
 *
 * JSON parse errors ARE logged (to Server console) but still return null,
 * since corrupt data shouldn't crash the page.
 */
export function getSocialPulse(showId: string): SocialPulsePayload | null {
  if (!showId) return null;
  const filePath = path.join(PUBLIC_SHOWS_DIR, `${showId}.social.json`);

  let raw: string;
  try {
    raw = fs.readFileSync(filePath, 'utf-8');
  } catch {
    // ENOENT is the common case — no social data yet for this show.
    return null;
  }

  let parsed: SocialPulsePayload;
  try {
    parsed = JSON.parse(raw) as SocialPulsePayload;
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn(`[data-social-pulse] Failed to parse ${filePath}: ${(err as Error).message}`);
    return null;
  }

  // Suppress stale data: the weekly fetcher only refreshes open/previews shows,
  // so an upcoming/closed show keeps a frozen `.social.json` forever. `u` is the
  // fetchedAt ISO timestamp in the compact schema. See isFreshPulse / the
  // School Girls incident. Callers should ALSO status-gate (open/previews) so a
  // recently-closed show's still-fresh card doesn't linger past closing.
  if (!isFreshPulse(parsed.u)) return null;

  return parsed;
}

/**
 * Lightweight runtime-shape guard for a parsed social-pulse file. A file
 * missing any of these required fields would otherwise blow up `sort`
 * (NaN) or crash the card component at render time. We'd rather skip a
 * malformed file than render the page as broken.
 */
function isValidRawPulse(raw: unknown): raw is RawSocialPulse {
  if (!raw || typeof raw !== 'object') return false;
  const r = raw as Record<string, unknown>;
  return (
    typeof r.showId === 'string' &&
    typeof r.showTitle === 'string' &&
    typeof r.market === 'string' &&
    typeof r.tier === 'string' &&
    typeof r.volume === 'number' &&
    typeof r.positivePct === 'number' &&
    !Number.isNaN(r.volume) &&
    !Number.isNaN(r.positivePct)
  );
}

/**
 * Read every RAW social-pulse file in data/social-pulse/ and return the
 * parsed payloads. Files beginning with `_` (like `_budget.json`) are
 * treated as internal bookkeeping and skipped. Malformed files are
 * warned-and-skipped rather than crashing the build.
 *
 * Safe to call from React server components at build time.
 */
function readAllRawSocialPulses(): RawSocialPulse[] {
  let files: string[];
  try {
    files = fs.readdirSync(SOCIAL_PULSE_DIR);
  } catch {
    return [];
  }

  const out: RawSocialPulse[] = [];
  for (const name of files) {
    if (!name.endsWith('.json')) continue;
    if (name.startsWith('_')) continue; // _budget.json and similar
    try {
      const raw = fs.readFileSync(path.join(SOCIAL_PULSE_DIR, name), 'utf-8');
      const parsed = JSON.parse(raw);
      if (!isValidRawPulse(parsed)) {
        // eslint-disable-next-line no-console
        console.warn(`[data-social-pulse] Skipping ${name}: missing required fields`);
        continue;
      }
      out.push(parsed);
    } catch (err) {
      // eslint-disable-next-line no-console
      console.warn(`[data-social-pulse] Failed to parse ${name}: ${(err as Error).message}`);
    }
  }
  return out;
}

/**
 * Returns the top N trending shows for a given market, ranked by
 * `compositeScore` (volume × positivePct / 100 — computed by
 * compute-social-pulse-ranks.js, or recomputed here if that field is
 * missing).
 *
 * Exclusions:
 *   - tier === 'Hidden' (below MIN_MENTIONS_FOR_CARD — not enough signal)
 *   - volume < MIN_TRENDING_VOLUME (see constant doc — page-specific floor)
 *   - stale fetches (fetchedAt older than MAX_SOCIAL_PULSE_AGE_DAYS) — a frozen
 *     file from an upcoming/closed show would otherwise rank on stale volume
 *   - showIds not present in `knownShowIds` (prevents dead-end rows for
 *     shows in the pulse corpus but missing from shows.json — e.g. an
 *     upcoming show the social scraper picked up before the show record
 *     was created)
 *
 * Tie-breaking: sort is `compositeScore` desc, `volume` desc, `showId` asc —
 * fully deterministic across OSes so SSR output is stable between CI and
 * local builds.
 *
 * Callers MUST pass `knownShowIds` (typically from `getAllShows()`) so the
 * orphan filter can run. To allow over-fetching so the caller can safely
 * take the top N even if a handful are filtered downstream, the function
 * returns up to `limit` results — but the `knownShowIds` filter already
 * runs internally, so the top-N slice is already orphan-free.
 */
export function getTopTrendingShows(
  market: 'Broadway' | 'West End',
  knownShowIds: ReadonlySet<string>,
  limit: number = 10,
): TrendingPick[] {
  return readAllRawSocialPulses()
    .filter(
      (p) =>
        p.market === market &&
        p.tier !== 'Hidden' &&
        p.volume >= MIN_TRENDING_VOLUME &&
        isFreshPulse(p.fetchedAt) &&
        knownShowIds.has(p.showId),
    )
    .map<TrendingPick>((p) => ({
      ...p,
      compositeScore:
        typeof p.compositeScore === 'number'
          ? p.compositeScore
          : (p.volume * p.positivePct) / 100,
    }))
    .sort((a, b) => {
      if (b.compositeScore !== a.compositeScore) return b.compositeScore - a.compositeScore;
      if (b.volume !== a.volume) return b.volume - a.volume;
      return a.showId.localeCompare(b.showId);
    })
    .slice(0, limit);
}

/**
 * Most recent `fetchedAt` across all social-pulse files — used to display
 * an "Updated X" line on the /trending page. Returns null if there's no data.
 */
export function getTrendingLastUpdated(): string | null {
  const all = readAllRawSocialPulses();
  if (all.length === 0) return null;
  let latest = 0;
  for (const p of all) {
    const t = Date.parse(p.fetchedAt || '');
    if (!Number.isNaN(t) && t > latest) latest = t;
  }
  return latest > 0 ? new Date(latest).toISOString() : null;
}
