/**
 * Social Pulse data loader — reads the compact sibling public file
 * generated by scripts/fetch-social-pulse.js.
 *
 * We read from a SIBLING file (public/data/shows/{id}.social.json) rather
 * than the main show JSON to avoid race conditions with the nightly
 * generate-mobile-show-details.js rebuild — see that script's comment
 * plus the plan-review pre-mortem scenario.
 *
 * Returns null if the file doesn't exist (show never scraped, or scraper
 * hasn't run yet). The card component renders nothing for null.
 */

import fs from 'fs';
import path from 'path';

import type { SocialPulsePayload } from '@/components/show-page/SocialPulseCard';

const PUBLIC_SHOWS_DIR = path.join(process.cwd(), 'public', 'data', 'shows');

/**
 * Synchronously reads the social pulse payload for a show. Safe to call
 * from React server components and getStaticProps equivalents.
 *
 * File-not-found is NOT an error — most shows won't have a file yet, and
 * any that do will have been generated by the weekly workflow. We return
 * null silently and let the card component no-op.
 *
 * JSON parse errors ARE logged (to Server console) but still return null,
 * since corrupt data shouldn't crash the page.
 */
export function getSocialPulse(showId: string): SocialPulsePayload | null {
  if (!showId) return null;
  const filePath = path.join(PUBLIC_SHOWS_DIR, `${showId}.social.json`);

  let raw: string;
  try {
    raw = fs.readFileSync(filePath, 'utf-8');
  } catch {
    // ENOENT is the common case — no social data yet for this show.
    return null;
  }

  try {
    return JSON.parse(raw) as SocialPulsePayload;
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn(`[data-social-pulse] Failed to parse ${filePath}: ${(err as Error).message}`);
    return null;
  }
}
