// Core data module — show scoring, queries, directors, theaters, best-of, browse
// Imports: shows.json (~1.3 MB), reviews.json (~3.8 MB), audience.json (~8 KB), buzz.json (~7 KB)
// Also imports getShowGrosses from data-grosses for browse page performance sort

import {
  computeShowData,
  ComputedShow,
  RawShow,
  RawReview,
  RawAudience,
  RawBuzzThread,
} from './engine';

import type { Director, Theater, TheaterStructuredTips, TheaterVenueScores, TheaterAccessibility, TheaterExternalLinks, BestOfCategory, BestOfList, BrowseList } from './data-types';
import { getShowGrosses } from './data-grosses';
import { getAudienceBuzz } from './data-audience';
import { getShowCommercial } from './data-commercial';
import { getShowAwards } from './data-awards';
import { BROWSE_PAGES, BrowsePageConfig, BrowseFilterContext, getAllBrowseSlugs as getBrowseSlugsFromConfig } from '@/config/browse-pages';
// Import raw data (loaded at build time for static generation)
import showsData from '../../data/shows.json';
import reviewsData from '../../data/reviews.json';
import audienceData from '../../data/audience.json';
import buzzData from '../../data/buzz.json';
// Pre-computed blog reviews for scoring (generated by prebuild)
import blogReviewsData from '../../data/blog-reviews-for-scoring.json';
// LLM-generated related show recommendations
import relatedShowsData from '../../data/related-shows.json';
// Theater metadata (capacity, tips)
import theaterMetaData from '../../data/theater-metadata.json';

// Type the imported data
const shows: RawShow[] = showsData.shows as RawShow[];
const baseReviews: RawReview[] = reviewsData.reviews as RawReview[];
const audience: RawAudience[] = audienceData.audience as RawAudience[];
const buzz: RawBuzzThread[] = buzzData.threads as RawBuzzThread[];

// Inject blog reviews as Tier 3 critic reviews
const reviews: RawReview[] = [
  ...baseReviews,
  ...(blogReviewsData.reviews as RawReview[]),
];

// Cache for computed shows
let computedShowsCache: ComputedShow[] | null = null;

/**
 * Get all shows with computed scores
 */
export function getAllShows(): ComputedShow[] {
  if (computedShowsCache) return computedShowsCache;

  computedShowsCache = shows.map(show =>
    computeShowData(show, reviews, audience, buzz)
  );

  return computedShowsCache;
}

/**
 * Check if a show belongs to Broadway (default category).
 * Shows with no category or category='broadway' are Broadway shows.
 */
function isBroadwayShow(show: ComputedShow): boolean {
  return !show.category || show.category === 'broadway';
}

/**
 * Get all Broadway shows (excludes off-Broadway and west-end from public listings).
 * Use getAllShows() for internal queries that need all shows (e.g., static page generation).
 */
export function getBroadwayShows(): ComputedShow[] {
  return getAllShows().filter(isBroadwayShow);
}

/**
 * Get all London shows (West End + Off-West End)
 */
export function getWestEndShows(): ComputedShow[] {
  return getAllShows().filter(show => show.category === 'west-end' || show.category === 'off-west-end');
}

/**
 * Get all Off-Broadway shows
 */
export function getOffBroadwayShows(): ComputedShow[] {
  return getAllShows().filter(show => show.category === 'off-broadway');
}

/**
 * Get Off-West End shows only (excludes West End proper)
 */
export function getOffWestEndShows(): ComputedShow[] {
  return getAllShows().filter(show => show.category === 'off-west-end');
}

/**
 * Get market stats for the header market picker
 */
export function getMarketStats() {
  const bwShows = getBroadwayShows();
  const weShows = getWestEndShows();
  const bwOpen = bwShows.filter(s => s.status === 'open' || s.status === 'previews');
  const weOpen = weShows.filter(s => s.status === 'open' || s.status === 'previews');
  return {
    nyc: {
      openShows: bwOpen.length,
      theaters: new Set(bwOpen.map(s => s.venue).filter(Boolean)).size,
    },
    westEnd: {
      openShows: weOpen.length,
      theaters: new Set(weOpen.map(s => s.venue).filter(Boolean)).size,
    },
  };
}

/**
 * Get shows filtered by status (excludes off-Broadway from public listings)
 */
export function getShowsByStatus(status: 'open' | 'closed' | 'previews' | 'all', options?: { includeOffBroadway?: boolean }): ComputedShow[] {
  const allShows = getAllShows();
  const includeOB = options?.includeOffBroadway ?? false;
  const filtered = includeOB ? allShows : allShows.filter(isBroadwayShow);
  if (status === 'all') return filtered;
  return filtered.filter(show => show.status === status);
}

/**
 * Get currently running shows (default homepage view — Broadway only)
 */
export function getCurrentShows(): ComputedShow[] {
  return getShowsByStatus('open');
}

/**
 * Get a single show by slug
 */
export function getShowBySlug(slug: string): ComputedShow | undefined {
  return getAllShows().find(show => show.slug === slug);
}

/**
 * Get a single show by ID
 */
export function getShowById(id: string): ComputedShow | undefined {
  return getAllShows().find(show => show.id === id);
}

/**
 * Get all show slugs (for static generation)
 */
export function getAllShowSlugs(): string[] {
  return shows.map(show => show.slug);
}

/**
 * Get shows sorted by composite score (excludes off-Broadway from public listings)
 */
export function getShowsSortedByCompositeScore(ascending = false): ComputedShow[] {
  return [...getAllShows()].filter(isBroadwayShow).sort((a, b) => {
    const scoreA = a.compositeScore ?? -1;
    const scoreB = b.compositeScore ?? -1;
    return ascending ? scoreA - scoreB : scoreB - scoreA;
  });
}

/**
 * Get data freshness info
 */
export function getDataFreshness() {
  return {
    showsLastUpdated: showsData._meta.lastUpdated,
    reviewsLastUpdated: reviewsData._meta.lastUpdated,
    audienceLastUpdated: audienceData._meta.lastUpdated,
    buzzLastUpdated: buzzData._meta.lastUpdated,
  };
}

/**
 * Get raw data counts for stats
 */
export function getDataStats() {
  const broadwayShows = getBroadwayShows();
  const totalReviews = broadwayShows.reduce((sum, show) => sum + (show.criticScore?.reviewCount || 0), 0);

  // Count unique outlets and critics from Broadway reviews only (consistent with show counts)
  const broadwayIds = new Set(broadwayShows.map(s => s.id));
  const broadwayReviews = baseReviews.filter(r => broadwayIds.has(r.showId));
  const uniqueOutlets = new Set(broadwayReviews.map(r => r.outletId));
  const uniqueCritics = new Set(broadwayReviews.map(r => r.criticName).filter(Boolean));

  return {
    totalShows: broadwayShows.filter(s => (s.criticScore?.reviewCount || 0) > 0).length,
    openShows: broadwayShows.filter(s => s.status === 'open').length,
    closedShows: broadwayShows.filter(s => s.status === 'closed').length,
    totalReviews,
    totalOutlets: uniqueOutlets.size,
    totalCritics: uniqueCritics.size,
    totalAudiencePlatforms: audience.length,
    totalBuzzThreads: buzz.length,
  };
}

/**
 * Get the most recent data update timestamp for a show
 * Returns ISO string of the most recent update across core data sources
 */
export function getShowLastUpdated(showId: string): string | null {
  const timestamps: Date[] = [];

  try {
    if (showsData._meta?.lastUpdated) {
      timestamps.push(new Date(showsData._meta.lastUpdated));
    }
  } catch { /* ignore */ }

  try {
    if (reviewsData._meta?.lastUpdated) {
      timestamps.push(new Date(reviewsData._meta.lastUpdated));
    }
  } catch { /* ignore */ }

  try {
    if (audienceData._meta?.lastUpdated) {
      timestamps.push(new Date(audienceData._meta.lastUpdated));
    }
  } catch { /* ignore */ }

  try {
    if (buzzData._meta?.lastUpdated) {
      timestamps.push(new Date(buzzData._meta.lastUpdated));
    }
  } catch { /* ignore */ }

  if (timestamps.length === 0) return null;

  const mostRecent = new Date(Math.max(...timestamps.map(d => d.getTime())));
  return mostRecent.toISOString();
}

/**
 * Get upcoming shows (in previews) - sorted by soonest opening date first.
 * Requires opening date (excludes undated announced shows).
 */
export function getUpcomingShows(): ComputedShow[] {
  return getBroadwayShows()
    .filter(show => (show.status === 'previews' || show.status === 'upcoming') && show.openingDate)
    .sort((a, b) => new Date(a.openingDate).getTime() - new Date(b.openingDate).getTime());
}

// ============================================
// Director Queries
// ============================================

export function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

/**
 * Get all unique directors with their shows
 */
export function getAllDirectors(): Director[] {
  const allShows = getBroadwayShows();
  const directorMap = new Map<string, ComputedShow[]>();

  for (const show of allShows) {
    const directors = show.creativeTeam?.filter(m =>
      m.role.toLowerCase().includes('director') &&
      !m.role.toLowerCase().includes('music director') &&
      !m.role.toLowerCase().includes('artistic director')
    ) || [];

    for (const director of directors) {
      const existing = directorMap.get(director.name) || [];
      existing.push(show);
      directorMap.set(director.name, existing);
    }
  }

  return Array.from(directorMap.entries()).map(([name, shows]) => {
    const scoredShows = shows.filter(s => s.criticScore?.score);
    const avgScore = scoredShows.length > 0
      ? Math.round(scoredShows.reduce((sum, s) => sum + (s.criticScore?.score || 0), 0) / scoredShows.length)
      : null;

    return {
      name,
      slug: slugify(name),
      shows,
      avgScore,
      showCount: shows.length,
    };
  }).sort((a, b) => b.showCount - a.showCount);
}

/**
 * Get a single director by slug
 */
export function getDirectorBySlug(slug: string): Director | undefined {
  return getAllDirectors().find(d => d.slug === slug);
}

/**
 * Get all director slugs (for static generation)
 */
export function getAllDirectorSlugs(): string[] {
  return getAllDirectors().map(d => d.slug);
}

// ============================================
// Theater Queries
// ============================================

/**
 * Get all unique theaters with their shows (memoized)
 */
let _theatersCache: Theater[] | null = null;
export function getAllTheaters(): Theater[] {
  if (_theatersCache) return _theatersCache;

  const allShows = getBroadwayShows();
  const theaterMap = new Map<string, { shows: ComputedShow[]; address?: string }>();

  for (const show of allShows) {
    const existing = theaterMap.get(show.venue) || { shows: [], address: show.theaterAddress };
    existing.shows.push(show);
    if (show.theaterAddress) existing.address = show.theaterAddress;
    theaterMap.set(show.venue, existing);
  }

  const meta = theaterMetaData as Record<string, { capacity?: number; tips?: string; yearBuilt?: number; operator?: string; formerNames?: string[]; structuredTips?: TheaterStructuredTips; images?: { exterior?: string; interior?: string; attribution?: string }; venueScores?: Omit<TheaterVenueScores, 'overall'>; accessibility?: TheaterAccessibility; externalLinks?: TheaterExternalLinks }>;

  _theatersCache = Array.from(theaterMap.entries())
    .filter(([name]) => !name.startsWith('_'))
    .map(([name, data]) => {
      const currentShow = data.shows.find(s => s.status === 'open' || s.status === 'previews' || s.status === 'upcoming');
      const theaterMeta = meta[name];

      // Compute overall venue score from individual dimensions
      const rawScores = theaterMeta?.venueScores;
      let venueScores: TheaterVenueScores | undefined;
      if (rawScores) {
        const dims = [rawScores.sightlines, rawScores.sound, rawScores.comfort, rawScores.ambiance, rawScores.facilities].filter((v): v is number => v != null);
        venueScores = {
          ...rawScores,
          overall: dims.length > 0 ? Math.round((dims.reduce((a, b) => a + b, 0) / dims.length) * 10) / 10 : undefined,
        };
      }

      return {
        name,
        slug: slugify(name),
        address: data.address,
        capacity: theaterMeta?.capacity,
        yearBuilt: theaterMeta?.yearBuilt,
        operator: theaterMeta?.operator,
        formerNames: theaterMeta?.formerNames,
        tips: theaterMeta?.tips,
        structuredTips: theaterMeta?.structuredTips,
        images: theaterMeta?.images,
        venueScores,
        accessibility: theaterMeta?.accessibility,
        externalLinks: theaterMeta?.externalLinks,
        currentShow,
        allShows: data.shows.sort((a, b) => {
          if (!a.openingDate && !b.openingDate) return 0;
          if (!a.openingDate) return 1;
          if (!b.openingDate) return -1;
          return new Date(b.openingDate).getTime() - new Date(a.openingDate).getTime();
        }),
        showCount: data.shows.length,
      };
    }).sort((a, b) => b.showCount - a.showCount);

  return _theatersCache;
}

/**
 * Get a single theater by slug
 */
export function getTheaterBySlug(slug: string): Theater | undefined {
  return getAllTheaters().find(t => t.slug === slug);
}

/**
 * Get all theater slugs (for static generation)
 */
export function getAllTheaterSlugs(): string[] {
  return getAllTheaters().map(t => t.slug);
}

// ============================================
// Best-of List Queries
// ============================================

const BEST_OF_CONFIG: Record<BestOfCategory, { title: string; description: string; filter: (show: ComputedShow) => boolean }> = {
  'musicals': {
    title: 'Best Broadway Musicals',
    description: 'Every Broadway musical ranked by aggregated critic scores from NYT, Variety, Vulture & 400+ outlets. See which are must-sees right now. Updated weekly.',
    filter: (show) => show.type === 'musical' && show.status === 'open',
  },
  'plays': {
    title: 'Best Broadway Plays',
    description: 'Every Broadway play ranked by aggregated critic scores from 400+ outlets. Find the must-see dramas and comedies playing now.',
    filter: (show) => show.type === 'play' && show.status === 'open',
  },
  'new-shows': {
    title: 'Best New Broadway Shows',
    description: 'The highest-rated Broadway shows that opened this season, ranked by aggregated critic scores from NYT, Variety, Vulture & 400+ outlets.',
    filter: (show) => {
      const openDate = new Date(show.openingDate);
      const now = new Date();
      const seasonStartYear = now.getMonth() >= 8 ? now.getFullYear() : now.getFullYear() - 1;
      const seasonStart = new Date(`${seasonStartYear}-09-01`);
      return show.status === 'open' && openDate >= seasonStart;
    },
  },
  'highest-rated': {
    title: 'Top 10 Highest Rated Broadway Shows',
    description: 'The 10 highest-rated Broadway shows right now based on aggregated critic scores from NYT, Variety, Vulture & 400+ outlets. Updated weekly.',
    filter: (show) => show.status === 'open' && show.criticScore?.score !== undefined,
  },
  'family': {
    title: 'Best Broadway Shows for Families',
    description: 'The best Broadway shows for kids and families, ranked by critics. Find age-appropriate musicals and plays the whole family will love.',
    filter: (show) => {
      const ageRec = show.ageRecommendation?.toLowerCase() || '';
      const tags = show.tags?.map(t => t.toLowerCase()) || [];
      return show.status === 'open' && (
        ageRec.includes('all ages') ||
        ageRec.includes('ages 6') ||
        ageRec.includes('ages 8') ||
        tags.includes('family')
      );
    },
  },
  'comedy': {
    title: 'Best Broadway Comedies',
    description: 'The funniest shows on Broadway right now, ranked by aggregated critic scores from 400+ outlets. Find the laughs you need. Updated weekly.',
    filter: (show) => {
      const tags = show.tags?.map(t => t.toLowerCase()) || [];
      return show.status === 'open' && tags.includes('comedy');
    },
  },
  'drama': {
    title: 'Best Broadway Dramas',
    description: 'The best dramas on Broadway right now, ranked by aggregated critic scores from 400+ outlets. Powerful plays currently captivating audiences and critics alike.',
    filter: (show) => {
      const tags = show.tags?.map(t => t.toLowerCase()) || [];
      return show.status === 'open' && tags.includes('drama');
    },
  },
};

/**
 * Get a best-of list by category
 */
export function getBestOfList(category: BestOfCategory): BestOfList | undefined {
  const config = BEST_OF_CONFIG[category];
  if (!config) return undefined;

  const allShows = getBroadwayShows();
  const filteredShows = allShows
    .filter(config.filter)
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .slice(0, 10);

  return {
    category,
    title: config.title,
    description: config.description,
    shows: filteredShows,
  };
}

/**
 * Get all best-of categories (for static generation)
 */
export function getAllBestOfCategories(): BestOfCategory[] {
  return Object.keys(BEST_OF_CONFIG) as BestOfCategory[];
}

// ============================================
// Browse Page Queries
// ============================================

/**
 * Get filtered and sorted shows for a browse page
 */
export function getBrowseList(slug: string): BrowseList | undefined {
  const config = BROWSE_PAGES[slug];
  if (!config) return undefined;

  const allShows = config.source === 'west-end' ? getWestEndShows()
    : config.source === 'off-broadway' ? getOffBroadwayShows()
    : config.source === 'off-west-end' ? getOffWestEndShows()
    : getBroadwayShows();

  // Context for data-dependent filters and custom sorts
  const ctx: BrowseFilterContext = { getAudienceBuzz, getShowCommercial, getShowAwards, getShowGrosses };

  let filteredShows = config.dataFilter
    ? allShows.filter(show => config.dataFilter!(show, ctx))
    : config.filter
    ? allShows.filter(config.filter)
    : allShows;

  // customSort and sort are mutually exclusive — customSort skips the sort switch
  if (config.customSort) {
    filteredShows = config.customSort(filteredShows, ctx);
  } else if (config.sort === 'score') {
    filteredShows = filteredShows.sort((a, b) => {
      const aScore = a.criticScore?.score;
      const bScore = b.criticScore?.score;
      if (aScore != null && bScore == null) return -1;
      if (aScore == null && bScore != null) return 1;
      if (aScore == null && bScore == null) return 0;
      return bScore! - aScore!;
    });
  } else if (config.sort === 'opening-date') {
    filteredShows = filteredShows.sort((a, b) => {
      if (!a.openingDate && !b.openingDate) return 0;
      if (!a.openingDate) return 1;
      if (!b.openingDate) return -1;
      return new Date(b.openingDate).getTime() - new Date(a.openingDate).getTime();
    });
  } else if (config.sort === 'opening-date-asc') {
    filteredShows = filteredShows.sort((a, b) => {
      if (!a.openingDate && !b.openingDate) return 0;
      if (!a.openingDate) return 1;
      if (!b.openingDate) return -1;
      return new Date(a.openingDate).getTime() - new Date(b.openingDate).getTime();
    });
  } else if (config.sort === 'closing-date') {
    filteredShows = filteredShows.sort((a, b) => {
      if (!a.closingDate) return 1;
      if (!b.closingDate) return -1;
      return new Date(a.closingDate).getTime() - new Date(b.closingDate).getTime();
    });
  } else if (config.sort === 'title') {
    filteredShows = filteredShows.sort((a, b) =>
      a.title.localeCompare(b.title)
    );
  } else if (config.sort === 'performances') {
    filteredShows = filteredShows.sort((a, b) => {
      const aGrosses = getShowGrosses(a.slug);
      const bGrosses = getShowGrosses(b.slug);
      const aPerf = aGrosses?.allTime?.performances ?? 0;
      const bPerf = bGrosses?.allTime?.performances ?? 0;
      return bPerf - aPerf;
    });
  }

  if (config.limit) {
    filteredShows = filteredShows.slice(0, config.limit);
  }

  return {
    config,
    shows: filteredShows,
  };
}

/**
 * Get all browse page slugs for static generation
 */
export function getAllBrowseSlugs(): string[] {
  return getBrowseSlugsFromConfig();
}

/**
 * Get related shows — LLM-generated lookup with algorithmic fallback
 */
// Strip year suffix to get base title for same-show detection
function baseTitle(title: string): string {
  return title.toLowerCase().replace(/\s*\(\d{4}\)\s*$/, '').trim();
}

function isSameShow(a: ComputedShow, b: ComputedShow): boolean {
  return a.id === b.id || baseTitle(a.title) === baseTitle(b.title);
}

export function getRelatedShows(show: ComputedShow, limit = 6): ComputedShow[] {
  const entry = (relatedShowsData as Record<string, unknown> & { shows: Record<string, { relatedIds: string[]; relatedOpenIds?: string[]; relatedClosedIds?: string[] }> }).shows?.[show.id];
  if (entry?.relatedIds?.length) {
    const allShows = getAllShows();
    const idMap = new Map(allShows.map(s => [s.id, s]));
    const slugMap = new Map(allShows.map(s => [s.slug, s]));
    const showMarket = show.category || 'broadway';
    return entry.relatedIds
      .map((id: string) => idMap.get(id) || slugMap.get(id))
      .filter((s): s is ComputedShow => s != null && !isSameShow(s, show) && (s.category || 'broadway') === showMarket)
      .slice(0, limit);
  }
  return getRelatedShowsAlgorithmic(show, limit);
}

export function getRelatedShowsOpen(show: ComputedShow, limit = 6): ComputedShow[] {
  const entry = (relatedShowsData as Record<string, unknown> & { shows: Record<string, { relatedOpenIds?: string[] }> }).shows?.[show.id];
  if (entry?.relatedOpenIds?.length) {
    const allShows = getAllShows();
    const idMap = new Map(allShows.map(s => [s.id, s]));
    const slugMap = new Map(allShows.map(s => [s.slug, s]));
    const showMarket = show.category || 'broadway';
    return entry.relatedOpenIds
      .map((id: string) => idMap.get(id) || slugMap.get(id))
      .filter((s): s is ComputedShow => s != null && (s.status === 'open' || s.status === 'previews' || s.status === 'upcoming') && !isSameShow(s, show) && (s.category || 'broadway') === showMarket)
      .slice(0, limit);
  }
  // Fallback: filter algorithmic results to open/previews/upcoming
  return getRelatedShowsAlgorithmic(show, limit * 3)
    .filter(s => s.status === 'open' || s.status === 'previews' || s.status === 'upcoming')
    .slice(0, limit);
}

export function getRelatedShowsClosed(show: ComputedShow, limit = 6): ComputedShow[] {
  const entry = (relatedShowsData as Record<string, unknown> & { shows: Record<string, { relatedClosedIds?: string[] }> }).shows?.[show.id];
  if (entry?.relatedClosedIds?.length) {
    const allShows = getAllShows();
    const idMap = new Map(allShows.map(s => [s.id, s]));
    const slugMap = new Map(allShows.map(s => [s.slug, s]));
    const showMarket = show.category || 'broadway';
    return entry.relatedClosedIds
      .map((id: string) => idMap.get(id) || slugMap.get(id))
      .filter((s): s is ComputedShow => s != null && s.status === 'closed' && !isSameShow(s, show) && (s.category || 'broadway') === showMarket)
      .slice(0, limit);
  }
  // Fallback: filter algorithmic results to closed
  return getRelatedShowsAlgorithmic(show, limit * 3)
    .filter(s => s.status === 'closed')
    .slice(0, limit);
}

/**
 * Find other productions of the same show across markets/years
 */
export function getOtherProductions(show: ComputedShow): ComputedShow[] {
  const normalize = (t: string) => t.toLowerCase().replace(/[\u2018\u2019\u2032'']/g, "'").replace(/[^\w\s']/g, '').trim();
  const baseTitle = normalize(show.title);
  const marketOrder: Record<string, number> = { broadway: 0, 'west-end': 1, 'off-west-end': 2, 'off-broadway': 3 };
  return getAllShows()
    .filter(s => s.id !== show.id && normalize(s.title) === baseTitle && (s.category || 'broadway') !== (show.category || 'broadway'))
    .sort((a, b) => {
      const catA = marketOrder[(a.category || 'broadway')] ?? 3;
      const catB = marketOrder[(b.category || 'broadway')] ?? 3;
      if (catA !== catB) return catA - catB;
      return (b.openingDate || '').localeCompare(a.openingDate || '');
    });
}

/**
 * Algorithmic fallback for shows not in the LLM-generated JSON
 */
function getRelatedShowsAlgorithmic(show: ComputedShow, limit = 6): ComputedShow[] {
  const allShows = getAllShows();

  // Precompute creative team lookup (name → role)
  const currentCreatives = new Map<string, string>();
  for (const m of show.creativeTeam || []) {
    currentCreatives.set(m.name.toLowerCase(), m.role.toLowerCase());
  }

  const currentTags = new Set(show.tags || []);
  const currentYear = show.openingDate ? new Date(show.openingDate).getFullYear() : 2020;
  const currentScore = show.criticScore?.score ?? null;

  // Score bands for proximity matching
  const getBand = (score: number | null) => {
    if (score === null) return -1;
    if (score >= 90) return 3;
    if (score >= 75) return 2;
    if (score >= 60) return 1;
    return 0;
  };
  const currentBand = getBand(currentScore);

  // Thematic vs structural tags
  const thematicTags = new Set(['comedy', 'drama', 'romantic', 'family', 'historical', 'fantasy', 'thriller', 'biographical']);
  const structuralTags = new Set(['jukebox', 'immersive', 'one-person-show', 'concert', 'revue']);

  // Role weights for creative team matching
  const roleWeight = (role: string): number => {
    const r = role.toLowerCase();
    if (r === 'director') return 8;
    if (r === 'book' || r === 'playwright' || r === 'composer' || r === 'music' || r === 'lyrics' || r === 'lyricist') return 7;
    if (r === 'choreographer') return 5;
    return 2;
  };

  const showCategory = show.category || 'broadway';
  const scored = allShows
    .filter(s => !isSameShow(s, show) && (s.criticScore?.reviewCount ?? 0) >= 5 && (s.category || 'broadway') === showCategory)
    .map(candidate => {
      let score = 0;

      // Type match (musical/play) — strong signal
      if (candidate.type === show.type) score += 10;

      // Creative team overlap (role-weighted)
      for (const member of candidate.creativeTeam || []) {
        if (currentCreatives.has(member.name.toLowerCase())) {
          score += roleWeight(member.role);
        }
      }

      // Tag overlap (category-weighted)
      for (const tag of candidate.tags || []) {
        if (!currentTags.has(tag)) continue;
        if (thematicTags.has(tag)) score += 4;
        else if (structuralTags.has(tag)) score += 2;
        // Skip meta tags like 'tony-winner', 'lottery', 'rush'
      }

      // Score band proximity
      const candidateBand = getBand(candidate.criticScore?.score ?? null);
      if (currentBand >= 0 && candidateBand >= 0) {
        if (candidateBand === currentBand) score += 3;
        else if (Math.abs(candidateBand - currentBand) === 1) score += 1;
      }

      // Temporal proximity
      const candidateYear = candidate.openingDate ? new Date(candidate.openingDate).getFullYear() : 2020;
      const yearDiff = Math.abs(currentYear - candidateYear);
      if (yearDiff <= 2) score += 3;
      else if (yearDiff <= 5) score += 1;

      // Currently open/previews boost
      if (candidate.status === 'open' || candidate.status === 'previews' || candidate.status === 'upcoming') score += 3;

      return { show: candidate, score };
    })
    .filter(({ score }) => score >= 12) // Minimum threshold — must match on type + at least one other signal
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);

  return scored.map(s => s.show);
}

// Export types
export type { ComputedShow };
export type { BrowsePageConfig } from '@/config/browse-pages';
