#!/usr/bin/env node
'use strict';
// scripts/codex/sync-skills.js: publish Claude's skills and slash-command
// checklists to Codex (.agents/skills/<name>/SKILL.md).
//
// BRO-4745: Codex discovers skills in .agents/skills, Claude in .claude/skills
// and .claude/commands. A hand copy of verify-opening-night already sat in
// .agents/skills at v1.1.0 while Claude's was v1.2.0, so the Codex side is
// generated, never edited. tests/unit/codex-parity.test.mjs fails when the
// committed output differs from renderSkills(), so a Claude-side change that
// skips `node scripts/codex/sync-skills.js` cannot land.
//
// Usage: node scripts/codex/sync-skills.js [--check]

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const OUT_DIR = path.join(REPO_ROOT, '.agents', 'skills');
const HEADER = '<!-- GENERATED by scripts/codex/sync-skills.js from {{SRC}}. Edit the source, then re-run the script. -->';
const CODEX_NOTE = [
  '> Codex note: this is the same checklist Claude follows as `/{{NAME}}`. Where it says to launch a',
  '> Claude subagent (Task/Agent tool) or call another skill, do that step yourself in this session,',
  '> or run it as a separate `codex exec`. Every other rule applies to you unchanged.',
].join('\n');

function yamlString(s) {
  return `"${String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function splitFrontmatter(text) {
  const m = /^---\n([\s\S]*?)\n---\n?/.exec(text);
  return m ? { front: m[1], body: text.slice(m[0].length) } : { front: null, body: text };
}

// Returns Map<relativeOutPath, content> for everything under .agents/skills.
function renderSkills(root = REPO_ROOT) {
  const out = new Map();
  const skillsDir = path.join(root, '.claude', 'skills');
  const commandsDir = path.join(root, '.claude', 'commands');

  for (const name of fs.existsSync(skillsDir) ? fs.readdirSync(skillsDir).sort() : []) {
    const dir = path.join(skillsDir, name);
    if (!fs.statSync(dir).isDirectory()) continue;
    // Match the real directory entry: on macOS's case-insensitive disk
    // existsSync('SKILL.md') is true for a skill.md source.
    const entry = fs.readdirSync(dir).find((f) => f.toLowerCase() === 'skill.md');
    if (!entry) continue;
    const src = path.join(dir, entry);
    const rel = path.relative(root, src);
    const { front, body } = splitFrontmatter(fs.readFileSync(src, 'utf8'));
    const fm = front || `name: ${name}\ndescription: ${yamlString(name)}`;
    out.set(`${name}/SKILL.md`, `---\n${fm}\n---\n${HEADER.replace('{{SRC}}', rel)}\n\n${CODEX_NOTE.replace('{{NAME}}', name)}\n\n${body}`);
    // Supporting files (e.g. scraper-reference/references/*.md) ride along verbatim.
    const walk = (d) => {
      for (const f of fs.readdirSync(d).sort()) {
        const p = path.join(d, f);
        if (fs.statSync(p).isDirectory()) walk(p);
        else if (p.toLowerCase() !== src.toLowerCase()) out.set(`${name}/${path.relative(dir, p)}`, fs.readFileSync(p, 'utf8'));
      }
    };
    walk(dir);
  }

  for (const file of fs.existsSync(commandsDir) ? fs.readdirSync(commandsDir).sort() : []) {
    if (!file.endsWith('.md')) continue;
    const name = file.slice(0, -3);
    if (out.has(`${name}/SKILL.md`)) continue; // a real skill of the same name wins
    const src = path.join(commandsDir, file);
    const { front, body } = splitFrontmatter(fs.readFileSync(src, 'utf8'));
    const firstLine = (body.split('\n').find((l) => l.trim()) || name).trim();
    const fm = front && /^description:/m.test(front)
      ? (/^name:/m.test(front) ? front : `name: ${name}\n${front}`)
      : `name: ${name}\ndescription: ${yamlString(`Claude's /${name} checklist. ${firstLine}`)}`;
    out.set(`${name}/SKILL.md`, `---\n${fm}\n---\n${HEADER.replace('{{SRC}}', path.relative(root, src))}\n\n${CODEX_NOTE.replace('{{NAME}}', name)}\n\n${body}`);
  }
  return out;
}

function listExisting(dir, base = dir) {
  if (!fs.existsSync(dir)) return [];
  const files = [];
  for (const f of fs.readdirSync(dir)) {
    const p = path.join(dir, f);
    if (fs.statSync(p).isDirectory()) files.push(...listExisting(p, base));
    else files.push(path.relative(base, p));
  }
  return files;
}

// { stale: [paths whose content differs or is missing], extra: [paths with no source] }
function diffSkills(root = REPO_ROOT) {
  const want = renderSkills(root);
  const dir = path.join(root, '.agents', 'skills');
  const have = new Set(listExisting(dir));
  const stale = [...want].filter(([rel, content]) => !have.has(rel) || fs.readFileSync(path.join(dir, rel), 'utf8') !== content).map(([rel]) => rel);
  const extra = [...have].filter((rel) => !want.has(rel));
  return { stale, extra };
}

function main() {
  if (process.argv.includes('--check')) {
    const { stale, extra } = diffSkills();
    if (stale.length || extra.length) {
      console.error(`Codex skills out of date. Run: node scripts/codex/sync-skills.js\n stale: ${stale.join(', ') || 'none'}\n extra: ${extra.join(', ') || 'none'}`);
      process.exit(1);
    }
    console.log('Codex skills in sync.');
    return;
  }
  const want = renderSkills();
  for (const rel of listExisting(OUT_DIR)) if (!want.has(rel)) fs.unlinkSync(path.join(OUT_DIR, rel));
  for (const [rel, content] of want) {
    const p = path.join(OUT_DIR, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
  }
  console.log(`Wrote ${want.size} files to .agents/skills`);
}

if (require.main === module) main();

module.exports = { renderSkills, diffSkills };
