// Server component — loads data at build time, passes serialized props to client
import fs from 'fs';
import crypto from 'crypto';
import { Suspense } from 'react';
import type { Metadata } from 'next';
import { getBroadwayShows, getOffBroadwayShows, getNotableOffBroadwayShows, getWestEndShows, getOperaShows, getDataStats, getUpcomingShows, getNYTCriticsPickShowIds, getMarketStats } from '@/lib/data-core';
import { getAwardWinnerSets } from '@/lib/data-awards';
import type { ComputedShow } from '@/lib/data-types';
import { serializeShowForClient } from '@/lib/serialize-show';
import { hasEnoughReviews } from '@/config/score-buckets';
import { BASE_URL, generateHomepageFAQSchema } from '@/lib/seo';
import { getOptimizedImageUrl } from '@/lib/images';
import path from 'path';
import HomePageClient from '@/components/HomePageClient';
import type { HomepageShow, FeaturedRowData } from '@/components/HomePageClient';
import FeaturedRowServer from '@/components/FeaturedRowServer';
import FeaturedSpotSlim from '@/components/FeaturedSpotSlim';
import { getTonyTrackRecord, isTonyPromoActive, isBtcPromoActive } from '@/lib/data-tony-predictions';

const homeOgImageUrl = `${BASE_URL}/og/home.png`;
const currentYear = new Date().getFullYear();

export const metadata: Metadata = {
  title: `Broadway Scorecard — Best Broadway Shows ${currentYear} | Aggregated Critic Reviews & Ratings`,
  description: 'Find the best Broadway shows with scores aggregated from every major critic. Compare ratings from The New York Times, Vulture, Variety, and 400+ outlets. Updated daily.',
  alternates: {
    canonical: BASE_URL,
  },
  openGraph: {
    type: 'website',
    siteName: 'Broadway Scorecard',
    title: `Broadway Scorecard — Best Broadway Shows ${currentYear}`,
    description: 'Find the best Broadway shows with scores aggregated from every major critic. Compare ratings from The New York Times, Vulture, Variety, and 400+ outlets.',
    url: BASE_URL,
    images: [{ url: homeOgImageUrl, width: 1200, height: 630, alt: 'Broadway Scorecard — Aggregated Critic Scores for Every Broadway Show' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: `Broadway Scorecard — Best Broadway Shows ${currentYear}`,
    description: 'Aggregated critic scores for every Broadway show. Compare ratings from 400+ outlets.',
    images: [{ url: homeOgImageUrl, width: 1200, height: 630, alt: 'Broadway Scorecard — Aggregated Critic Scores for Every Broadway Show' }],
  },
};

function serializeShow(show: ComputedShow): HomepageShow {
  return serializeShowForClient(show);
}

export default function HomePage() {
  const allShows = getBroadwayShows();
  const stats = getDataStats();
  const upcomingShows = getUpcomingShows();
  // Live headline accuracy — same number rendered on the season-specific
  // predictions page. Lives here so the homepage promo never drifts.
  const tonyTrackRecord = getTonyTrackRecord(allShows);
  // Tony promo auto-hides 2 days after the ceremony.
  const tonyPromoActive = isTonyPromoActive();
  const btcPromoActive = isBtcPromoActive();

  // Only pass active (non-closed) shows as props — archive is lazy-loaded from
  // public/data/homepage-archive.json (generated by scripts/generate-homepage-archive.js)
  const broadwayActive = allShows.filter(s => s.status !== 'closed');
  // Mix a small, capped set of NOTABLE off-Broadway shows into the main grid so
  // it doesn't go stale when Broadway openings are sparse. Each renders with an
  // "Off-Bway" category badge (showCategoryBadge in ShowCardList). The OB market
  // pill count + /off-broadway page are unaffected — this only seeds the grid.
  // Notability rule: src/lib/homepage-notability.ts.
  const broadwayIds = new Set(broadwayActive.map(s => s.id));
  const notableOffBroadway = getNotableOffBroadwayShows()
    .filter(s => s.status !== 'closed' && !broadwayIds.has(s.id));
  const activeShows = [...broadwayActive, ...notableOffBroadway];
  const archiveFile = fs.readFileSync(process.cwd() + '/public/data/homepage-archive.json');
  const archiveHash = crypto.createHash('md5').update(archiveFile).digest('hex').slice(0, 8);
  const obShows = getOffBroadwayShows().filter(s =>
    (s.status === 'open' || s.status === 'previews') &&
    s.type !== 'opera' && // opera gets its own "At the Met" shelf
    s.criticScore && s.criticScore.reviewCount !== undefined && s.criticScore.reviewCount >= 5
  );
  const weShows = getWestEndShows().filter(s =>
    s.criticScore && s.criticScore.reviewCount !== undefined && s.criticScore.reviewCount >= 3
  );
  // Opera shelf: small universe (typically 3-4 Met productions running concurrently),
  // so the reviewCount threshold is lower than OB (5) / WE (3). Currently-running
  // productions only — the /opera page shows the full archive including closed runs.
  const operaShelfShows = getOperaShows().filter(s =>
    (s.status === 'open' || s.status === 'previews') &&
    s.criticScore && s.criticScore.score && s.criticScore.reviewCount !== undefined && s.criticScore.reviewCount >= 2
  );

  // Precompute "Best Recent Shows" server-side for both preload links and SSR featured row
  const twelveMonthsAgo = new Date();
  twelveMonthsAgo.setMonth(twelveMonthsAgo.getMonth() - 12);
  const shelfScoreFilter = (s: typeof allShows[number]) =>
    s.criticScore?.score && hasEnoughReviews(
      s.criticScore.reviewCount ?? 0, s.category,
      (s.criticScore.tier1Count ?? 0) + (s.criticScore.tier2Count ?? 0)
    );

  const bestRecentShows = allShows
    .filter(s => (s.type === 'musical' || s.type === 'play') && s.status === 'open' && new Date(s.openingDate) >= twelveMonthsAgo && shelfScoreFilter(s))
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .slice(0, 10)
    .map(serializeShow);

  // Pre-compute ALL featured rows server-side to avoid 700+ item iterations on client hydration
  const tonyWinnersShows = allShows
    .filter(s => s.status === 'open' && s.tags?.some(t => t.toLowerCase() === 'tony-winner'))
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  const dateNightShowsList = allShows
    .filter(s => {
      if (s.status !== 'open') return false;
      const tags = s.tags?.map(t => t.toLowerCase()) || [];
      const ageRec = s.ageRecommendation?.toLowerCase() || '';
      return (tags.includes('romantic') || tags.includes('drama')) && !ageRec.includes('ages 6') && !ageRec.includes('ages 8');
    })
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  const kidsShowsList = allShows
    .filter(s => {
      if (s.status !== 'open') return false;
      const tags = s.tags?.map(t => t.toLowerCase()) || [];
      const ageRec = s.ageRecommendation?.toLowerCase() || '';
      return tags.includes('family') || tags.includes('accessible') || ageRec.includes('ages 6') || ageRec.includes('ages 8') || ageRec.includes('all ages');
    })
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  const now = new Date();
  const shortDate = (d: string) => new Date(d + 'T12:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric' });

  const closingSoonShowsList = allShows
    .filter(s => {
      if (s.status !== 'open' || !s.closingDate) return false;
      const closing = new Date(s.closingDate);
      const diffDays = Math.ceil((closing.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
      return diffDays > 0 && diffDays <= 120;
    })
    .sort((a, b) => new Date(a.closingDate!).getTime() - new Date(b.closingDate!).getTime())
    .map(s => ({ ...serializeShow(s), subtitle: `Closes ${shortDate(s.closingDate!)}`, subtitleColor: 'text-amber-400' }));

  const jukeboxMusicalsList = allShows
    .filter(s => s.status === 'open' && s.tags?.some(t => t.toLowerCase() === 'jukebox'))
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  const bestOffBroadwayList = obShows
    .filter(s => s.criticScore?.score && hasEnoughReviews(
      s.criticScore.reviewCount ?? 0, s.category,
      (s.criticScore.tier1Count ?? 0) + (s.criticScore.tier2Count ?? 0)
    ))
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  // --- New shelves: Previews, Lotteries, Rush, Box Office, Sold Out, West End ---

  // In Previews — sorted by opening date (soonest first), null dates last
  const inPreviewsList = allShows
    .filter(s => s.status === 'previews')
    .sort((a, b) => (new Date(a.openingDate || '2099-01-01').getTime()) - (new Date(b.openingDate || '2099-01-01').getTime()))
    .map(s => ({ ...serializeShow(s), subtitle: s.openingDate ? `Opens ${shortDate(s.openingDate)}` : undefined, subtitleColor: 'text-gray-400' }));

  // Lottery/Rush data (fallback to empty if file missing)
  let lrShows: Record<string, { lottery?: { price?: number }; specialLottery?: { price?: number }; rush?: { price?: number }; digitalRush?: { price?: number } }> = {};
  try {
    const lotteryRushData = JSON.parse(
      fs.readFileSync(path.join(process.cwd(), 'data/lottery-rush.json'), 'utf8')
    );
    lrShows = lotteryRushData.shows || {};
  } catch { /* lottery-rush.json missing — shelves will be empty */ }

  function lotterySubtitle(showId: string): string | undefined {
    const lr = lrShows[showId];
    if (!lr) return undefined;
    const price = lr.specialLottery?.price ?? lr.lottery?.price;
    return price ? `$${Math.round(price)} lottery` : undefined;
  }

  function rushSubtitle(showId: string): string | undefined {
    const lr = lrShows[showId];
    if (!lr) return undefined;
    const prices = [lr.rush?.price, lr.digitalRush?.price].filter((p): p is number => p != null);
    const price = prices.length ? Math.min(...prices) : undefined;
    return price ? `$${Math.round(price)} rush` : undefined;
  }

  // Broadway Lotteries — open BW shows with lottery, sorted by score
  const lotteryShowsList = allShows
    .filter(s => s.status === 'open' && lrShows[s.id]?.lottery)
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(s => ({ ...serializeShow(s), subtitle: lotterySubtitle(s.id) }));

  // Rush Tickets — open BW shows with rush or digital rush, sorted by score
  const rushShowsList = allShows
    .filter(s => s.status === 'open' && (lrShows[s.id]?.rush || lrShows[s.id]?.digitalRush))
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(s => ({ ...serializeShow(s), subtitle: rushSubtitle(s.id) }));

  // Box Office data (fallback to empty if file missing)
  let grossesShows: Record<string, { thisWeek?: { gross?: number; capacity?: number } }> = {};
  try {
    const grossesData = JSON.parse(
      fs.readFileSync(path.join(process.cwd(), 'data/grosses.json'), 'utf8')
    );
    grossesShows = grossesData.shows || {};
  } catch { /* grosses.json missing — shelves will be empty */ }

  // Top Box Office This Week — sorted by weekly gross (highest first)
  const formatGross = (n: number) => n >= 1_000_000 ? `$${(n / 1_000_000).toFixed(1)}M` : `$${Math.round(n / 1_000)}K`;
  const topBoxOfficeList = allShows
    .filter(s => s.status === 'open' && grossesShows[s.slug]?.thisWeek?.gross)
    .sort((a, b) => (grossesShows[b.slug]?.thisWeek?.gross || 0) - (grossesShows[a.slug]?.thisWeek?.gross || 0))
    .map(s => ({ ...serializeShow(s), subtitle: formatGross(grossesShows[s.slug]!.thisWeek!.gross!), subtitleColor: 'text-gray-400' }));

  // Most Sold Out — sorted by capacity % (highest first)
  const mostSoldOutList = allShows
    .filter(s => s.status === 'open' && grossesShows[s.slug]?.thisWeek?.capacity)
    .sort((a, b) => (grossesShows[b.slug]?.thisWeek?.capacity || 0) - (grossesShows[a.slug]?.thisWeek?.capacity || 0))
    .map(s => ({ ...serializeShow(s), subtitle: `${Math.round(grossesShows[s.slug]!.thisWeek!.capacity!)}% capacity`, subtitleColor: 'text-gray-400' }));

  // Shows Starting Soon — upcoming (not yet in previews), sorted by previewsStartDate
  const startingSoonList = allShows
    .filter(s => s.status === 'upcoming' && (s.previewsStartDate || s.openingDate))
    .sort((a, b) => new Date(a.previewsStartDate || a.openingDate).getTime() - new Date(b.previewsStartDate || b.openingDate).getTime())
    .map(s => {
      const startDate = s.previewsStartDate || s.openingDate;
      return { ...serializeShow(s), subtitle: startDate ? `Starts ${shortDate(startDate)}` : undefined, subtitleColor: 'text-gray-400' };
    });

  // At the Met — currently-running opera productions with scores, sorted by score
  const bestOperaList = operaShelfShows
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  // Best of the West End — open WE shows with scores, sorted by score
  const bestWestEndList = weShows
    .filter(s => s.status === 'open' && s.criticScore?.score)
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  // NYT Critic's Picks — sourced from the authoritative spotlight page
  const nytPickIds = getNYTCriticsPickShowIds();
  const nytCriticsPicksList = nytPickIds.size > 0 ? allShows
    .filter(s => s.status === 'open' && nytPickIds.has(s.id))
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow) : [];

  const featuredRows: FeaturedRowData[] = [
    { title: 'Best Off-Broadway', shows: bestOffBroadwayList, viewAllHref: '/off-broadway' },
    // Opera shelf \u2014 Met universe is small (3-4 productions running), so minCount 2.
    // Positioned right after Off-Broadway so opera coverage is visible without
    // scrolling past 3 sections (acceptance criterion on Notion 362637c5-416f-8183).
    { title: 'At the Met', shows: bestOperaList, viewAllHref: '/opera', minCount: 2 },
    ...(nytCriticsPicksList.length > 0 ? [{ title: "New York Times Critic\u2019s Picks", shows: nytCriticsPicksList, viewAllHref: '/critics/outlets/the-new-york-times' }] : []),
    { title: 'In Previews / Opening Soon', shows: inPreviewsList, viewAllHref: '/browse/upcoming-broadway-shows', minCount: 1 },
    { title: 'Broadway Lotteries', shows: lotteryShowsList, viewAllHref: '/lotteries' },
    { title: 'Rush Tickets Available', shows: rushShowsList, viewAllHref: '/rush' },
    { title: 'Top Box Office This Week', shows: topBoxOfficeList, viewAllHref: '/box-office' },
    { title: 'Most Sold Out', shows: mostSoldOutList, viewAllHref: '/box-office' },
    { title: 'Shows Starting Soon', shows: startingSoonList, viewAllHref: '/browse/upcoming-broadway-shows' },
    { title: 'Best of the West End', shows: bestWestEndList, viewAllHref: '/west-end' },
    { title: 'Tony Winning Shows', shows: tonyWinnersShows, viewAllHref: '/browse/tony-winners-on-broadway' },
    { title: 'Perfect for Date Night', shows: dateNightShowsList, viewAllHref: '/browse/broadway-shows-for-date-night' },
    { title: 'Great for Kids', shows: kidsShowsList, viewAllHref: '/browse/broadway-shows-for-kids' },
    { title: 'Jukebox Musicals', shows: jukeboxMusicalsList, viewAllHref: '/browse/jukebox-musicals-on-broadway' },
    { title: 'Closing Soon', shows: closingSoonShowsList, viewAllHref: '/browse/broadway-shows-closing-soon' },
  ];

  const featuredPosterUrls = bestRecentShows
    .slice(0, 4)
    .map(s => {
      const img = s.images?.poster || s.images?.thumbnail;
      return img ? getOptimizedImageUrl(img, 'card') : null;
    })
    .filter((u): u is string => !!u);

  return (
    <>
      {featuredPosterUrls.map((url, i) => (
        <link key={`preload-${i}`} rel="preload" as="image" href={url} fetchPriority={i === 0 ? 'high' : undefined} />
      ))}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(generateHomepageFAQSchema(stats)) }}
      />
      {/* Server-rendered hero + featured row — LCP image appears in initial HTML, no JS needed */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 pt-5 sm:pt-12">
        <div className="mb-4 sm:mb-8">
          <h1 className="sr-only sm:not-sr-only sm:text-5xl lg:text-6xl font-extrabold text-white mb-4 sm:mb-5 tracking-tight">
            Broadway<span className="text-gradient">Scorecard</span><span className="text-xs text-gray-400 font-normal align-super ml-0.5">™</span>
          </h1>
          <p className="text-gray-400 text-lg sm:text-xl">
            Every show. Every review. One score.
          </p>
          <p className="text-gray-500 text-sm sm:text-base mt-1">
            {stats.totalShows.toLocaleString('en-US')} shows. {stats.totalReviews.toLocaleString('en-US')} critic reviews. And counting.
          </p>
        </div>
        {/* Above-fold slim promo — currently Tony predictions; swap to BTC by
            changing the props (BTC config kept below as a comment).
            Beat the Critics swap:
              <FeaturedSpotSlim
                eyebrow="Now playing"
                title="Think you know Broadway better than the critics?"
                ctaLabel="Make your picks"
                href="/beat-the-critics"
                accent="btc"
                stat={{ icon: '★', label: 'Beat the Critics' }}
              /> */}
        {tonyPromoActive && (
          <FeaturedSpotSlim
            eyebrow="Tony Awards 2026"
            title="Who will win Best Musical?"
            ctaLabel="See the predictions"
            href="/tony-awards/predictions/2025-2026"
            accent="gold"
            stat={{ value: `${tonyTrackRecord.pct}%`, label: 'Track record' }}
            trackingId="homepage_above_fold_tony_predictions"
          />
        )}
        <FeaturedRowServer shows={bestRecentShows} />
      </div>
      <Suspense>
        <HomePageClient
          shows={activeShows.map(serializeShow)}
          archiveHash={archiveHash}
          upcomingShows={upcomingShows.map(serializeShow)}
          offBroadwayShows={obShows.map(serializeShow)}
          westEndShows={weShows.map(serializeShow)}
          totalShows={stats.totalShows}
          totalReviews={stats.totalReviews}
          totalCritics={stats.totalCritics}
          totalOutlets={stats.totalOutlets}
          skipHero
          skipFirstMusicals
          featuredRows={featuredRows}
          marketOpenCounts={{
            broadway: getMarketStats().nyc.openShows,
            offBroadway: getMarketStats().offBroadway?.openShows ?? 0,
          }}
          awardWinnerSets={getAwardWinnerSets()}
          tonyTrackRecord={tonyTrackRecord}
          tonyPromoActive={tonyPromoActive}
          btcPromoActive={btcPromoActive}
        />
      </Suspense>
    </>
  );
}
