// Server component — loads data at build time, passes serialized props to client
import fs from 'fs';
import crypto from 'crypto';
import { Suspense } from 'react';
import type { Metadata } from 'next';
import { getBroadwayShows, getOffBroadwayShows, getWestEndShows, getDataStats, getUpcomingShows } from '@/lib/data-core';
import type { ComputedShow } from '@/lib/data-types';
import { getAudienceBuzz, getAudienceGrade, hasEnoughAudienceReviews } from '@/lib/data-audience';
import { hasEnoughReviews } from '@/config/score-buckets';
import { BASE_URL, generateHomepageFAQSchema } from '@/lib/seo';
import { getOptimizedImageUrl } from '@/lib/images';
import path from 'path';
import HomePageClient from '@/components/HomePageClient';
import type { HomepageShow, FeaturedRowData } from '@/components/HomePageClient';
import FeaturedRowServer from '@/components/FeaturedRowServer';

const homeOgImageUrl = `${BASE_URL}/og/home.png`;
const currentYear = new Date().getFullYear();

export const metadata: Metadata = {
  title: `Broadway Scorecard — Best Broadway Shows ${currentYear} | Aggregated Critic Reviews & Ratings`,
  description: 'Find the best Broadway shows with scores aggregated from every major critic. Compare ratings from The New York Times, Vulture, Variety, and 400+ outlets. Updated daily.',
  alternates: {
    canonical: BASE_URL,
  },
  openGraph: {
    title: `Broadway Scorecard — Best Broadway Shows ${currentYear}`,
    description: 'Find the best Broadway shows with scores aggregated from every major critic. Compare ratings from The New York Times, Vulture, Variety, and 400+ outlets.',
    url: BASE_URL,
    images: [{ url: homeOgImageUrl, width: 1200, height: 630, alt: 'Broadway Scorecard — Aggregated Critic Scores for Every Broadway Show' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: `Broadway Scorecard — Best Broadway Shows ${currentYear}`,
    description: 'Aggregated critic scores for every Broadway show. Compare ratings from 400+ outlets.',
    images: [{ url: homeOgImageUrl, width: 1200, height: 630, alt: 'Broadway Scorecard — Aggregated Critic Scores for Every Broadway Show' }],
  },
};

function serializeShow(show: ComputedShow): HomepageShow {
  const buzz = getAudienceBuzz(show.id);
  return {
    id: show.id,
    slug: show.slug,
    title: show.title,
    venue: show.venue,
    openingDate: show.openingDate,
    closingDate: show.closingDate ?? undefined,
    status: show.status,
    type: show.type,
    isRevival: show.isRevival ?? undefined,
    tags: show.tags,
    ageRecommendation: show.ageRecommendation ?? undefined,
    creativeTeam: show.creativeTeam,
    reviewYearNote: show.reviewYearNote ?? undefined,
    images: show.images,
    criticScore: show.criticScore
      ? { score: show.criticScore.score, reviewCount: show.criticScore.reviewCount, tier1Count: show.criticScore.tier1Count, tier2Count: show.criticScore.tier2Count }
      : undefined,
    audienceCombinedScore: buzz && hasEnoughAudienceReviews(buzz) ? buzz.combinedScore : null,
    audienceGrade: buzz && hasEnoughAudienceReviews(buzz) ? getAudienceGrade(buzz.combinedScore) : null,
    category: show.category,
  };
}

export default function HomePage() {
  const allShows = getBroadwayShows();
  const stats = getDataStats();
  const upcomingShows = getUpcomingShows();

  // Only pass active (non-closed) shows as props — archive is lazy-loaded from
  // public/data/homepage-archive.json (generated by scripts/generate-homepage-archive.js)
  const activeShows = allShows.filter(s => s.status !== 'closed');
  const archiveFile = fs.readFileSync(process.cwd() + '/public/data/homepage-archive.json');
  const archiveHash = crypto.createHash('md5').update(archiveFile).digest('hex').slice(0, 8);
  const obShows = getOffBroadwayShows().filter(s =>
    (s.status === 'open' || s.status === 'previews') &&
    s.criticScore && s.criticScore.reviewCount !== undefined && s.criticScore.reviewCount >= 5
  );
  const weShows = getWestEndShows().filter(s =>
    s.criticScore && s.criticScore.reviewCount !== undefined && s.criticScore.reviewCount >= 3
  );

  // Precompute "Best Recent Shows" server-side for both preload links and SSR featured row
  const twelveMonthsAgo = new Date();
  twelveMonthsAgo.setMonth(twelveMonthsAgo.getMonth() - 12);
  const bestRecentShows = allShows
    .filter(s => (s.type === 'musical' || s.type === 'play') && s.status === 'open' && new Date(s.openingDate) >= twelveMonthsAgo && s.criticScore?.score)
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .slice(0, 10)
    .map(serializeShow);

  // Pre-compute ALL featured rows server-side to avoid 700+ item iterations on client hydration
  const tonyWinnersShows = allShows
    .filter(s => s.status === 'open' && s.tags?.some(t => t.toLowerCase() === 'tony-winner'))
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  const dateNightShowsList = allShows
    .filter(s => {
      if (s.status !== 'open') return false;
      const tags = s.tags?.map(t => t.toLowerCase()) || [];
      const ageRec = s.ageRecommendation?.toLowerCase() || '';
      return (tags.includes('romantic') || tags.includes('drama')) && !ageRec.includes('ages 6') && !ageRec.includes('ages 8');
    })
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  const kidsShowsList = allShows
    .filter(s => {
      if (s.status !== 'open') return false;
      const tags = s.tags?.map(t => t.toLowerCase()) || [];
      const ageRec = s.ageRecommendation?.toLowerCase() || '';
      return tags.includes('family') || tags.includes('accessible') || ageRec.includes('ages 6') || ageRec.includes('ages 8') || ageRec.includes('all ages');
    })
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  const now = new Date();
  const closingSoonShowsList = allShows
    .filter(s => {
      if (s.status !== 'open' || !s.closingDate) return false;
      const closing = new Date(s.closingDate);
      const diffDays = Math.ceil((closing.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
      return diffDays > 0 && diffDays <= 60;
    })
    .sort((a, b) => new Date(a.closingDate!).getTime() - new Date(b.closingDate!).getTime())
    .map(serializeShow);

  const jukeboxMusicalsList = allShows
    .filter(s => s.status === 'open' && s.tags?.some(t => t.toLowerCase() === 'jukebox'))
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  const bestOffBroadwayList = obShows
    .filter(s => s.criticScore?.score && hasEnoughReviews(
      s.criticScore.reviewCount ?? 0, s.category,
      (s.criticScore.tier1Count ?? 0) + (s.criticScore.tier2Count ?? 0)
    ))
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  // --- New shelves: Previews, Lotteries, Rush, Box Office, Sold Out, West End ---

  // In Previews — sorted by opening date (soonest first)
  const inPreviewsList = allShows
    .filter(s => s.status === 'previews')
    .sort((a, b) => new Date(a.openingDate).getTime() - new Date(b.openingDate).getTime())
    .map(serializeShow);

  // Lottery/Rush data
  const lotteryRushData = JSON.parse(
    fs.readFileSync(path.join(process.cwd(), 'data/lottery-rush.json'), 'utf8')
  );
  const lrShows = lotteryRushData.shows || {};

  // Broadway Lotteries — open BW shows with lottery, sorted by score
  const lotteryShowsList = allShows
    .filter(s => s.status === 'open' && lrShows[s.id]?.lottery)
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  // Rush Tickets — open BW shows with rush or digital rush, sorted by score
  const rushShowsList = allShows
    .filter(s => s.status === 'open' && (lrShows[s.id]?.rush || lrShows[s.id]?.digitalRush))
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  // Box Office data
  const grossesData = JSON.parse(
    fs.readFileSync(path.join(process.cwd(), 'data/grosses.json'), 'utf8')
  );
  const grossesShows = grossesData.shows || {};

  // Top Box Office This Week — sorted by weekly gross (highest first)
  const topBoxOfficeList = allShows
    .filter(s => s.status === 'open' && grossesShows[s.slug]?.thisWeek?.gross)
    .sort((a, b) => (grossesShows[b.slug].thisWeek.gross || 0) - (grossesShows[a.slug].thisWeek.gross || 0))
    .map(serializeShow);

  // Most Sold Out — sorted by capacity % (highest first)
  const mostSoldOutList = allShows
    .filter(s => s.status === 'open' && grossesShows[s.slug]?.thisWeek?.capacity)
    .sort((a, b) => (grossesShows[b.slug].thisWeek.capacity || 0) - (grossesShows[a.slug].thisWeek.capacity || 0))
    .map(serializeShow);

  // Best of the West End — open WE shows with scores, sorted by score
  const bestWestEndList = weShows
    .filter(s => s.status === 'open' && s.criticScore?.score)
    .sort((a, b) => (b.criticScore?.score || 0) - (a.criticScore?.score || 0))
    .map(serializeShow);

  const featuredRows: FeaturedRowData[] = [
    { title: 'Best Off-Broadway', shows: bestOffBroadwayList, viewAllHref: '/off-broadway' },
    { title: 'In Previews', shows: inPreviewsList, viewAllHref: '/browse/upcoming-broadway-shows' },
    { title: 'Broadway Lotteries', shows: lotteryShowsList, viewAllHref: '/lotteries' },
    { title: 'Rush Tickets Available', shows: rushShowsList, viewAllHref: '/rush' },
    { title: 'Top Box Office This Week', shows: topBoxOfficeList, viewAllHref: '/box-office' },
    { title: 'Most Sold Out', shows: mostSoldOutList, viewAllHref: '/box-office' },
    { title: 'Upcoming', shows: upcomingShows.map(serializeShow), viewAllHref: '/browse/upcoming-broadway-shows' },
    { title: 'Best of the West End', shows: bestWestEndList, viewAllHref: '/west-end' },
    { title: 'Tony Winning Shows', shows: tonyWinnersShows, viewAllHref: '/browse/tony-winners-on-broadway' },
    { title: 'Perfect for Date Night', shows: dateNightShowsList, viewAllHref: '/browse/broadway-shows-for-date-night' },
    { title: 'Great for Kids', shows: kidsShowsList, viewAllHref: '/browse/broadway-shows-for-kids' },
    { title: 'Jukebox Musicals', shows: jukeboxMusicalsList, viewAllHref: '/browse/jukebox-musicals-on-broadway' },
    { title: 'Closing Soon', shows: closingSoonShowsList, viewAllHref: '/browse/broadway-shows-closing-soon' },
  ];

  const featuredPosterUrls = bestRecentShows
    .slice(0, 4)
    .map(s => {
      const img = s.images?.poster || s.images?.thumbnail;
      return img ? getOptimizedImageUrl(img, 'card') : null;
    })
    .filter((u): u is string => !!u);

  return (
    <>
      {featuredPosterUrls.map((url, i) => (
        <link key={`preload-${i}`} rel="preload" as="image" href={url} fetchPriority={i === 0 ? 'high' : undefined} />
      ))}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(generateHomepageFAQSchema(stats)) }}
      />
      {/* Server-rendered hero + featured row — LCP image appears in initial HTML, no JS needed */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 pt-5 sm:pt-12">
        <div className="mb-4 sm:mb-8">
          <h1 className="sr-only sm:not-sr-only sm:text-5xl lg:text-6xl font-extrabold text-white mb-4 sm:mb-5 tracking-tight">
            Broadway<span className="text-gradient">Scorecard</span><span className="text-xs text-gray-400 font-normal align-super ml-0.5">™</span>
          </h1>
          <p className="text-gray-400 text-lg sm:text-xl">
            Every show. Every review. One score.
          </p>
          <p className="text-gray-500 text-sm sm:text-base mt-1">
            {stats.totalShows.toLocaleString()} shows. {stats.totalReviews.toLocaleString()} critic reviews. And counting.
          </p>
        </div>
        <FeaturedRowServer shows={bestRecentShows} />
      </div>
      <Suspense>
        <HomePageClient
          shows={activeShows.map(serializeShow)}
          archiveHash={archiveHash}
          upcomingShows={upcomingShows.map(serializeShow)}
          offBroadwayShows={obShows.map(serializeShow)}
          westEndShows={weShows.map(serializeShow)}
          totalShows={stats.totalShows}
          totalReviews={stats.totalReviews}
          skipHero
          skipFirstMusicals
          featuredRows={featuredRows}
        />
      </Suspense>
    </>
  );
}
