/**
 * Locks index — scans data/review-texts/*\/*.json for files that carry a
 * humanReviewScore lock and emits a flat audit array.
 *
 * Drives:
 *   - public/data/admin/locks.json (regenerated by rebuild-all-reviews.js)
 *   - /admin/locks UI (browses the audit table)
 *   - scripts/backfill-locked-reasons.js (finds files missing rationale)
 *
 * A "lock" here is a hard human override of the LLM ensemble's score. It is
 * NOT the same as humanReviewScoreProvisional (a pre-scoring placeholder) —
 * provisional scores are intentionally LLM-overridable in rebuild-helpers.js
 * getBestScore() and don't belong on an audit page that says "this score
 * came from a human, not the model."
 *
 * Output record shape:
 *   {
 *     showId, outletId, criticName, filename, url,
 *     lockedScore: number,            // humanReviewScore
 *     priorScore: number | null,      // llmScore.score at lock time
 *     lockedReason: string | null,    // explicit rationale (or null pre-backfill)
 *     lockedAt: string | null,        // ISO 8601
 *     lockedBy: string | null,        // operator email/identifier
 *     lockedAcrossTier: boolean | null,
 *     hasRationale: boolean,          // false ⇒ surface in backfill list
 *     publishDate: string | null,
 *   }
 */

const fs = require('fs');
const path = require('path');

const SHOW_DIR_SKIPLIST = new Set(['_pending', '.git']);

function isLockedFile(data) {
  if (!data || typeof data !== 'object') return false;
  const score = data.humanReviewScore;
  if (typeof score !== 'number' || score < 1 || score > 100) return false;
  // Provisional scores are LLM-overridable placeholders — exclude.
  if (data.humanReviewScoreProvisional === true) return false;
  return true;
}

function buildLockRecord(showId, filename, data) {
  const llmScore = (data.llmScore && typeof data.llmScore === 'object') ? data.llmScore : null;
  const priorScore = llmScore && typeof llmScore.score === 'number' ? llmScore.score : null;
  const lockedReason = typeof data.lockedReason === 'string' && data.lockedReason.trim()
    ? data.lockedReason.trim()
    : null;
  return {
    showId,
    outletId: typeof data.outletId === 'string' ? data.outletId : null,
    outlet: typeof data.outlet === 'string' ? data.outlet : null,
    criticName: typeof data.criticName === 'string' ? data.criticName : null,
    filename,
    url: typeof data.url === 'string' ? data.url : null,
    lockedScore: data.humanReviewScore,
    priorScore,
    lockedReason,
    lockedAt: typeof data.lockedAt === 'string' ? data.lockedAt : null,
    lockedBy: typeof data.lockedBy === 'string' ? data.lockedBy : null,
    lockedAcrossTier: typeof data.lockedAcrossTier === 'boolean' ? data.lockedAcrossTier : null,
    hasRationale: !!lockedReason,
    publishDate: typeof data.publishDate === 'string' ? data.publishDate : null,
  };
}

/**
 * Walk reviewTextsDir and return one lock record per locked review file.
 * Sorted by lockedAt desc (locks without lockedAt sink to the bottom).
 *
 * @param {string} reviewTextsDir Absolute path to data/review-texts/
 * @returns {Array<object>}
 */
function scanLocks(reviewTextsDir) {
  if (!fs.existsSync(reviewTextsDir)) return [];
  const records = [];
  const showDirs = fs.readdirSync(reviewTextsDir, { withFileTypes: true });
  for (const dirent of showDirs) {
    if (!dirent.isDirectory()) continue;
    if (SHOW_DIR_SKIPLIST.has(dirent.name)) continue;
    const showId = dirent.name;
    const showDir = path.join(reviewTextsDir, showId);
    let files;
    try {
      files = fs.readdirSync(showDir).filter((f) => f.endsWith('.json'));
    } catch {
      continue;
    }
    for (const filename of files) {
      const filePath = path.join(showDir, filename);
      let data;
      try {
        data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
      } catch {
        continue;
      }
      if (!isLockedFile(data)) continue;
      records.push(buildLockRecord(showId, filename, data));
    }
  }
  records.sort((a, b) => {
    if (a.lockedAt && b.lockedAt) return b.lockedAt.localeCompare(a.lockedAt);
    if (a.lockedAt) return -1;
    if (b.lockedAt) return 1;
    return a.showId.localeCompare(b.showId);
  });
  return records;
}

/**
 * Generate the locks.json index file.
 *
 * @param {object} opts
 * @param {string} opts.reviewTextsDir
 * @param {string} opts.outputPath        Absolute path to locks.json
 * @returns {{ count: number, withRationale: number, withoutRationale: number }}
 */
function writeLocksIndex({ reviewTextsDir, outputPath }) {
  const records = scanLocks(reviewTextsDir);
  const withRationale = records.filter((r) => r.hasRationale).length;
  const payload = {
    generatedAt: new Date().toISOString(),
    count: records.length,
    withRationale,
    withoutRationale: records.length - withRationale,
    locks: records,
  };
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(outputPath, JSON.stringify(payload, null, 2) + '\n');
  return {
    count: records.length,
    withRationale,
    withoutRationale: records.length - withRationale,
  };
}

module.exports = { scanLocks, writeLocksIndex, isLockedFile, buildLockRecord };
