/**
 * Head-to-head: Broadway Scorecard model vs GoldDerby's expert-pundit
 * predictions across all historical Tony cycles where both made picks.
 *
 * The point of this surface is to answer the "is your LOSO number just
 * backtest luck" question with an external benchmark. GoldDerby's predictions
 * are made by panels of theatre journalists pre-ceremony each year, so they
 * aren't tuned to past Tony outcomes — different methodology, same contests,
 * directly comparable on hit rate.
 *
 * Data sourced from `getGoldDerbyComparison()` which reads
 * data/analysis/gd-vs-broadwayscore.json (regenerated by
 * scripts/compare-gd-vs-broadwayscore.ts on every recipe change).
 */
import type { GoldDerbyComparison } from '@/lib/data-tony-predictions';

interface Props {
  data: GoldDerbyComparison;
}

export function ExpertsComparison({ data }: Props) {
  const { ours, goldDerby, sample, perCategory, weHitTheyMissed, theyHitWeMissed, weBeatThemCount, theyBeatUsCount } = data;

  return (
    <section className="rounded-xl border border-white/5 bg-surface-overlay p-5 sm:p-6">
      <div className="flex items-baseline justify-between gap-3 mb-3">
        <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-wider">vs GoldDerby&apos;s expert predictions</h2>
        <span className="text-[11px] text-gray-500">{sample.cycles} seasons &middot; {sample.races} races</span>
      </div>

      {/* Two-column hit rate */}
      <div className="grid grid-cols-2 gap-3 sm:gap-4 mb-5">
        <div className="rounded-lg border border-brand/30 bg-brand/[0.06] p-4 text-center">
          <div className="text-[11px] text-brand font-semibold uppercase tracking-wider mb-1">Broadway Scorecard</div>
          <div className="text-3xl sm:text-4xl font-bold text-white leading-none mb-1 tabular-nums">
            {ours.hits}<span className="text-gray-600 font-light mx-0.5">/</span>{ours.total}
          </div>
          <div className="text-sm text-gray-300 tabular-nums">{ours.pct}% match rate</div>
        </div>
        <div className="rounded-lg border border-white/8 bg-white/[0.02] p-4 text-center">
          <div className="text-[11px] text-gray-400 font-semibold uppercase tracking-wider mb-1">GoldDerby experts</div>
          <div className="text-3xl sm:text-4xl font-bold text-gray-200 leading-none mb-1 tabular-nums">
            {goldDerby.hits}<span className="text-gray-600 font-light mx-0.5">/</span>{goldDerby.total}
          </div>
          <div className="text-sm text-gray-300 tabular-nums">{goldDerby.pct}% match rate</div>
        </div>
      </div>

      {/* Head-to-head ledger */}
      <div className="grid grid-cols-2 gap-3 sm:gap-4 text-xs text-gray-300 mb-5">
        <div className="rounded-lg bg-white/[0.02] p-3">
          <div className="text-gray-500 mb-1">We picked the winner, they missed</div>
          <div className="text-xl font-bold text-emerald-400 tabular-nums">{weBeatThemCount} <span className="text-xs font-normal text-gray-400">race{weBeatThemCount === 1 ? '' : 's'}</span></div>
        </div>
        <div className="rounded-lg bg-white/[0.02] p-3">
          <div className="text-gray-500 mb-1">They picked the winner, we missed</div>
          <div className="text-xl font-bold text-amber-400 tabular-nums">{theyBeatUsCount} <span className="text-xs font-normal text-gray-400">race{theyBeatUsCount === 1 ? '' : 's'}</span></div>
        </div>
      </div>

      {/* Per-category */}
      <div className="mb-5">
        <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3">By category</h3>
        <div className="overflow-x-auto -mx-1">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-[11px] text-gray-500 uppercase tracking-wide">
                <th className="text-left font-medium pb-2 px-1">Category</th>
                <th className="text-right font-medium pb-2 px-1">Us</th>
                <th className="text-right font-medium pb-2 px-1">GoldDerby</th>
              </tr>
            </thead>
            <tbody>
              {perCategory.map(({ key, label, ours: oh, theirs, total }) => {
                const oursLeads = oh > theirs;
                const theyLead = theirs > oh;
                return (
                  <tr key={key} className="border-t border-white/5">
                    <td className="py-2 px-1 text-gray-300 whitespace-nowrap">{label}</td>
                    <td className={`text-right py-2 px-1 tabular-nums ${oursLeads ? 'text-emerald-400 font-semibold' : 'text-white'}`}>
                      {oh}/{total}
                    </td>
                    <td className={`text-right py-2 px-1 tabular-nums ${theyLead ? 'text-amber-400 font-semibold' : 'text-gray-300'}`}>
                      {theirs}/{total}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Specific races we differ on */}
      {(weHitTheyMissed.length > 0 || theyHitWeMissed.length > 0) && (
        <div className="grid sm:grid-cols-2 gap-3">
          {weHitTheyMissed.length > 0 && (
            <div>
              <h3 className="text-xs font-semibold text-emerald-400 uppercase tracking-wider mb-2">Races we caught, they missed</h3>
              <div className="space-y-1.5">
                {weHitTheyMissed.map(r => (
                  <div key={`${r.cycle}-${r.category}`} className="text-xs text-gray-300 rounded border border-emerald-500/15 bg-emerald-500/[0.03] p-2">
                    <div className="text-[10px] text-gray-500 mb-0.5">{r.cycle} &middot; {r.category}</div>
                    <div><span className="text-gray-500">Winner:</span> <span className="text-white">{r.winner}</span></div>
                    <div className="text-[11px]"><span className="text-gray-500">GoldDerby picked:</span> {r.gdPick}</div>
                  </div>
                ))}
              </div>
            </div>
          )}
          {theyHitWeMissed.length > 0 && (
            <div>
              <h3 className="text-xs font-semibold text-amber-400 uppercase tracking-wider mb-2">Races they caught, we missed</h3>
              <div className="space-y-1.5">
                {theyHitWeMissed.map(r => (
                  <div key={`${r.cycle}-${r.category}`} className="text-xs text-gray-300 rounded border border-amber-500/15 bg-amber-500/[0.03] p-2">
                    <div className="text-[10px] text-gray-500 mb-0.5">{r.cycle} &middot; {r.category}</div>
                    <div><span className="text-gray-500">Winner:</span> <span className="text-white">{r.winner}</span></div>
                    <div className="text-[11px]"><span className="text-gray-500">We picked:</span> {r.ourPick}</div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      <p className="text-[11px] text-gray-500 mt-5 pt-4 border-t border-white/5 leading-relaxed">
        GoldDerby publishes panel-of-experts predictions before each Tony ceremony. Their pundits are not tuned to past Tony outcomes; ours is. Same contests, different methodologies, directly comparable on whether the #1 pick won. Updated after each ceremony.
      </p>
    </section>
  );
}
