import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const { sanitizeShowScoreUrl } = require('../../scripts/lib/show-score-link.js');

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '../..');

test('sanitizeShowScoreUrl accepts real section pages', () => {
  for (const u of [
    'https://www.show-score.com/broadway-shows/other-desert-cities-broadway',
    'https://www.show-score.com/off-broadway-shows/some-show',
    'https://www.show-score.com/off-off-broadway-shows/some-show',
    'https://www.show-score.com/uk/some-show',
  ]) {
    assert.equal(sanitizeShowScoreUrl(u), u);
  }
});

test('sanitizeShowScoreUrl rejects the invented /show/<slug> pattern that 404s (BRO-4821)', () => {
  assert.equal(sanitizeShowScoreUrl('https://show-score.com/show/other-desert-cities'), null);
});

test('sanitizeShowScoreUrl rejects non-https, other hosts, bare sections and junk', () => {
  for (const u of [
    'http://www.show-score.com/broadway-shows/x',
    'https://evil.example/broadway-shows/x',
    'https://www.show-score.com/broadway-shows/',
    'https://www.show-score.com/',
    'not a url',
    '',
    null,
    undefined,
    42,
  ]) {
    assert.equal(sanitizeShowScoreUrl(u), null, String(u));
  }
});

test('every URL in data/show-score-urls.json is shippable to the app', (t) => {
  const file = path.join(root, 'data/show-score-urls.json');
  if (!fs.existsSync(file)) return t.skip('data/show-score-urls.json not present');
  const shows = JSON.parse(fs.readFileSync(file, 'utf-8')).shows || {};
  const bad = Object.entries(shows).filter(([, u]) => sanitizeShowScoreUrl(u) === null);
  assert.deepEqual(bad, []);
});

// The per-show JSON is regenerated by CI (rebuild-fast / rebuild-reviews), not by
// hand, so right after this change lands the committed files lack `u`. Once the
// first regeneration has put it on any show, every show with a tile and a known
// URL must carry it (and a valid one), so a partial or broken regenerate fails.
test('once generated per-show JSON carries au.sources.ss.u, every tile with a known URL has it', (t) => {
  const dir = path.join(root, 'public/data/shows');
  const urlsFile = path.join(root, 'data/show-score-urls.json');
  if (!fs.existsSync(dir) || !fs.existsSync(urlsFile)) return t.skip('generated data not present');
  const urls = JSON.parse(fs.readFileSync(urlsFile, 'utf-8')).shows || {};
  const withTile = [];
  for (const f of fs.readdirSync(dir).filter(n => n.endsWith('.json'))) {
    const d = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf-8'));
    if (d.au?.sources?.ss && urls[d.id]) withTile.push({ id: d.id, u: d.au.sources.ss.u });
  }
  if (!withTile.some(x => x.u)) return t.skip('per-show JSON not yet regenerated with ss.u');
  assert.deepEqual(withTile.filter(x => x.u !== urls[x.id]).map(x => x.id), []);
});
